src/VASSAL/counters/Labeler.java, src/VASSAL/script/expression/BeanShellExpression.java
Turned out the $..$ variables just wheren't being evalated at all on either the source or the targets. So this can't possibly be working in any module.
=> Bug 12952 - Evalute $..$ strings in Property Match expressions on source pce

src/VASSAL/counters/Deck.java
This appears to fix Bug 12951 where card ownership is lost when a Return to Deck - Send To Location is Undone through a face down Deck.
Logically, this statement is not required except for face-down draws from a Deck, but Deck.pieceRemoved() is called and handles this case anyway.
Will need thorough testing with Deck heavy modules.
=> Bug 12951 - Undo of cards back through a Deck results in incorrect

src/VASSAL/build/module/GameState.java, src/VASSAL/build/module/Inventory.java, src/VASSAL/counters/DragBuffer.java, src/VASSAL/counters/KeyBuffer.java, src/VASSAL/i18n/LocaleConfigurer.java, src/VASSAL/launch/ModuleManagerWindow.java
Minor refactoring replacing Collections.sort() with Java 8's list.sort()
=> Refactoring - replace Collections.sort() with list.sort()

src/VASSAL/counters/AreaOfEffect.java
Bug 13060. Shouldn't happen, but we are getting NPE's trying to generate the shape when a piece has no parent Map. Added defensive coding to check map is non-null before trying to use it.
=> Bug 13060 - Check unit is on a Map before trying to generate the Shape

.settings/.gitignore, src/VASSAL/build/module/GlobalOptions.java, src/VASSAL/counters/Translate.java, src/VASSAL/i18n/VASSAL.properties
This fix is a complete re-organisation of the Move Fixed Distance (MFD) Trait code. 
The 'batching' of moves is replaced by using the same method as SendToLocation to move each piece as required in the correct logical sequence. This now combines correctly with other commands and movements in Trigger Actions.
The original code is retained and can be enabled via a Preference. The default for the preference is OFF. Players who need the old behaviour (unlikely) will need to opt in.
This fix resolves the following issues (Bugs 1874, 1948, 2610, 4212):
- MFD no longer creates additional NullCommands when used in a Trigger. All Triggers now have a single undo.
- Multiple MFD commands applied to a unit by a Trigger Action now execute in the correct order and interact with other traits and …
=> Bug 12948 move fixed distance undo trigger issues

src/VASSAL/build/module/BasicCommandEncoder.java, src/VASSAL/build/module/map/DrawPile.java, src/VASSAL/counters/Deck.java
This is a first step towards making the Deck class testable, as right now it is not even possible to do a simple `new Deck()` without an existing GameModule object tree. After this change it will be possible to provide the Deck with a mocked GameModule upon instantiation.
=> Refactoring - decoupled Deck from static GameModule access

src/VASSAL/build/module/map/CounterDetailViewer.java, src/VASSAL/build/module/map/DrawPile.java, src/VASSAL/build/module/map/MovementReporter.java, src/VASSAL/build/module/map/PieceMover.java, src/VASSAL/build/module/map/StackMetrics.java, src/VASSAL/counters/Deck.java, src/VASSAL/counters/DragBuffer.java, src/VASSAL/counters/GlobalCommand.java, src/VASSAL/counters/KeyBuffer.java, src/VASSAL/counters/PieceIterator.java, src/VASSAL/counters/Restricted.java, src/VASSAL/counters/Stack.java, test/VASSAL/counters/StackTest.java
For now this is only for discussion as it will probably clash with PR #5.
I am not too happy with the naming, but the simpler `getPieces()` is already taken by the old enumeration method.
This change would have some nice side effects, most of the clients of `getPiecesIterator()` can be rewritten to use the new method, and the List.stream() allows other interesting code improvements.
The whole `PieceIterator` and `PieceFilter` can probably be removed altogether, in favor of this new method and `Predicate<GamePiece>` from the stream API.
=> Refactoring - added method Stack.asList

src/VASSAL/build/module/map/BoardPicker.java, src/VASSAL/build/module/map/SetupStack.java
Bug 12576 - if At-Start stack has owningBoard "Any", default to first selected board, not first allowable board. If no selected board is available, old default remains.
Recreated from previously closed pull request because I messed up and created it against my local master.
=> Bug 12576 Resolution

src/VASSAL/build/module/map/KeyBufferer.java, src/VASSAL/build/module/map/MapShader.java, src/VASSAL/build/module/map/PieceMover.java, src/VASSAL/counters/SendToLocation.java, src/VASSAL/script/ExpressionInterpreter.java
Some more places where the new Stack.asList() can be used instead of manual access of its contents. The loops that do not contain assignment to non-final variables use the more modern forEach() / stream() variants, rest uses the "traditional" handwritten foreach.
While I was at it, and my IDE went crazy and marked the whole class bright red because of this, I included a small fix of a reference to a non-existing Exception class in a javadoc.
=> Refactoring - use Stack.asList() instead of manual getPieceCount() / getPieceAt() access

src/VASSAL/counters/Stack.java, test/VASSAL/counters/StackTest.java
This should fix the bug mentioned in http://www.vassalengine.org/forum/viewtopic.php?f=3&t=11996
=> Revert Stack.asList to return a defensive copy of contained GamePieces

src/VASSAL/build/GameModule.java, src/VASSAL/build/module/Inventory.java, src/VASSAL/build/module/Map.java, src/VASSAL/build/module/PlayerRoster.java, src/VASSAL/counters/Deck.java, src/VASSAL/counters/Restricted.java, test/VASSAL/counters/DeckTest.java
Another step towards make the `Deck` testable. For now as a draft. The static access to `PlayerRoster` had to be removed, after that the first unit tests can be written.
The static `PlayerRoster.getInstance()` had to be resolved, I decided to make it a method of the `GameModule` as it is the container for a possible `PlayerRoster` instance.
The static `PlayerRoster.addSideChangeListener()` also had to be changed, I decided to make it a method of the `GameModule` as well. It needed access to the PlayerRoster's sideChangeListeners so `PlayerRoster` received a new accessor method for it. And now the `GameModule.addSideChangeListenerToPlayerRoster()` is simply a convenience method, maybe it makes sense to remove it entirely and have the clients do what it does now i.e. get the `PlayerRoster` …
=> Refactoring - make the Deck testable

pom.xml
Maven uses its own project version, this is now largely irrelevant but already appears in the CI build and might become more useful later on.
=> Updated the the project version for Maven

.travis.yml
A depth of 1 would probably be enough since we don't do anything with the git history during the build, but let's go with 3, just in case.
=> Set git clone depth to 3 in travis build configuration

src/main/java/VASSAL/tools/version/VassalVersionTokenizer.java, src/test/java/VASSAL/tools/version/VassalVersionTokenizerTest.java
Versions with a build number are incorrectly sorted before versions without a build number.
It should be the case that 3.3.1 < 3.3.1-42, but the version tokenizer has it the other way around.
=> Bug 13140: Versions with a build number are incorrectly sorted

src/test/resources/checkstyle-checks.xml
I have commented the INFO checks in the checkstyle settings xml, they will have to be added stepwise later on, once we get rid of the current WARN-level checks.
=> Checkstyle - ignore INFO-level checks

CHANGES, Makefile
The jdk.crypto.ec module is required to resolve HTTPS URLs. Add that to the module dependencies for jlink.
=> Bug 13143: HTTPS URLs fail to load (handshake_failure)

src/test/java/VASSAL/tools/io/ProcessCallableTest.java
This fails on Windows due to String "\n" not being translated to "\r\n".
=> Use System.lineSeparator() in ProcessCallableTest

src/main/java/VASSAL/build/GameModule.java, src/main/java/VASSAL/build/module/GlobalOptions.java, src/main/java/VASSAL/build/module/Map.java, src/main/java/VASSAL/build/module/map/PieceMover.java, src/main/resources/VASSAL/i18n/VASSAL.properties
Map's mouse listeners were translating the coordinates of mouse events from component coordinates to map coordinates before passing them on, but doing so in a way that actually overwrote the original event that awt DragGestureRecognizer was still using, resulting in an apples-to-oranges coordinate comparison that effectively reduced the dragThreshold to 1 at any zoom other than 100%. This is now fixed, and a user preference added to adjust the drag threshold (because 5 is still actually pretty damn tight)
=> Bug 13137 - Drag Threshold - fixes bug where drag threshold was effectively 1 pixel. Also allows user to adjust w/ preference.

src/test/java/VASSAL/tools/lang/MemoryUtilsTest.java
Build is broken on MacOSX due to this. I assume this was not tested on the other Unixes either, and it's not necessary to run this on non-Linuxes anyways.
=> Fixed build on non-linux unix e.g. MacOSX

pom.xml, src/test/java/VASSAL/build/MockModuleTest.java, src/test/java/VASSAL/counters/SerializeTest.java, src/test/java/VASSAL/tools/io/CompositeInputStreamTest.java, src/test/java/VASSAL/tools/io/RereadableInputStreamTest.java
This lets us drop our dependency on jmock-legacy.
=> Rewrote tests not to use org.jmock.lib.legacy.ClassImposteriser

src/main/java/VASSAL/build/AbstractBuildable.java, src/main/java/VASSAL/build/GameModule.java, src/main/java/VASSAL/build/module/ModuleExtension.java, src/main/java/VASSAL/build/module/dice/BonesDiceServer.java, src/main/java/VASSAL/build/module/documentation/BrowserHelpFile.java, src/main/java/VASSAL/launch/AbstractLaunchAction.java, src/main/java/VASSAL/launch/ModuleManager.java, src/main/java/VASSAL/launch/ModuleManagerWindow.java, src/main/java/VASSAL/tools/AudioSystemClip.java, src/main/java/VASSAL/tools/image/tilecache/ZipFileImageTiler.java, src/main/java/VASSAL/tools/io/IOUtils.java, src/main/java/VASSAL/tools/io/Tailer.java, src/main/java/VASSAL/tools/ipc/IPCMessageDispatcher.java, src/main/java/VASSAL/tools/ipc/IPCMessageReceiver.java, src/test/java/VASSAL/tools/ipc/IPCMessageDispatcherTest.java, src/test/java/VASSAL/tools/ipc/IPCMessageReceiverTest.java
Removes most of the leftover calls to closeQuietly(). In some cases this helped detangle the code and introduce detailed error messages where there was previously one catch-all error.
=> Removed calls to deprecated IOUtils.closeQuietly

src/main/java/VASSAL/build/module/Chatter.java
Found Depreciated swing calls in Chatter.java 
I'm not 100% on one or two things here:
1) I couldn't find these methods (over-ridden or otherwise) being called from anywhere else in the code, so I've assumed they are intended to be public, and should be depreciated, so I've
1.1) Marked them as depreciated
1.2) Made them call the new over-ridden methods
2) the new methods require floats, not ints, casting ints to floats is all good, but I've cast floats to int for the return from the depreciated call.. which is blasphemous.
Thoughts would be appreciated, so I can know what to do in this project in future.
=> Chatter depreciated calls

src/test/resources/checkstyle-checks.xml
This activates the next set of checks and sets their severity to either warning or error.
Violations considered **error** (currently none in the codebase):
- OuterTypeFilename
- IllegalTokenText
- AvoidStarImport
- OneTopLevelClass
- NoLineWrap (PACKAGE_DEF, IMPORT, STATIC_IMPORT)
- ArrayTypeStyle
- FallThrough
- UpperEll
- SeparatorWrap (ellipsis, array declarator)
- PackageName (format "^(VASSAL)|[a-z]+(\.[a-z][a-z0-9]*)*$")
- ClassTypeParameterName
- MethodTypeParameterName
- InterfaceTypeParameterName
Violations considered **warning** (currently several in the codebase):
- EmptyBlock (LITERAL_TRY, LITERAL_FINALLY, LITERAL_IF, LITERAL_ELSE, LITERAL_SWITCH)
- LeftCurly (various)
- ModifierOrder
- SeparatorWrap (dot, comma)
- NoFinalizer
- GenericWhitespace
=> Activate more checkstyle checks

src/main/java/VASSAL/build/module/GameState.java, src/main/resources/VASSAL/i18n/VASSAL.properties
Possibly we don't want this to fire for an online game, but afaik it would have fired before (in the paths where it actually fired) -- but the implementation had grown so full of weeds that it's hard to know what was really intended. Anyway it would be easy to just ignore this in an online game.
=> 13153 fix the start-a-log-file at beginning of game preference to work right, and give it a comprehensible name

Makefile
This commit fixes `make javadoc` so that it generates pages that return correct search results.
**PROBLEM DESCRIPTION**
`make javadoc` generates JavaDoc HTML documentation from the VASSAL source code. This documentation includes a SEARCH field in the upper-right corner of each page.  After filling in a search term in a browser and clicking on a search result, the browser follows a broken link. The page *does* exist, the link is just broken.
Example of the relative portion of an erroneous link:
```
javadoc/undefined/VASSAL/command/AddPiece.html
```
Correct link:
```
javadoc/VASSAL/command/AddPiece.html
```
**STEPS TO REPRODUCE PROBLEM**
1. From a command line, change to the root VASSAL project directory and run `make javadoc`
2. Use a browser to view `javadoc/index.html`
3. Enter …
=> Fix JavaDoc search feature

vassal-app/pom.xml
Upgraded miglayout-swing to 5.2. This recovers the patch I contributed o 4.2 which we lost when we switched to maven and picked up an unpatched 4.2 JAR. Fixes Bug 13205.
=> Bug 13205: Upgrade miglayout-swing to 5.2

vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
STEP 1 - Removed the pointless first dialog box from the "Retire" flow. This box added no actual additional choices, only added a needless extra step, especially for the common use case of "hotseat" players.
STEP 2 - Further improved the flow for Hotseat use case by offering the next "real" player slot (if one is available) as the default-selected option. Filtered out of the list are (a) player slots already occupied, and (b) player slots using any of the common names for "Solitaire" / "Solo" / "Referee".  If no available "real" slot is found, then the Observer option is selected as the default. 
Hotseat players can now click the button and hit Enter (or click Okay) to cycle to next player, which removes THREE extra clicks from their present flow. Meanwhile no other use cases should …
=> 3042 - Improved "Retire"/"Resign"/"Switch Sides" button flow.

vassal-app/src/test/resources/checkstyle-checks.xml
This change the severity level of all previously removed checkstyle violations from `warning` to `error`, except the one violation of the "no finalize()" rule.
And activates the next set of violations on the `warning` level, after this having no whitespace after `,`, `;`, `typecast`, `if`, `else`, `while`, `do`, `for` and the `do while` will be reported.
=> Increase checkstyle strictness

.travis.yml
Travis originates from the Ruby world and due to this history runs Maven twice in the default setting:
`./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`
`./mvnw test -B`
After this commit it will run Maven only once using `./mvnw clean test -B`.
=> Configure travis to run only one maven build

vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Minor refactoring.
`PredefinedSetup.isMenu()` is already checked in `PredefinedSetup.addPredefinedSetup()`, no need to check it again in the renderer.
=> Refactored WizardSupport

vassal-app/src/main/java/VASSAL/build/AutoConfigurable.java, vassal-app/src/main/java/VASSAL/build/Configurable.java, vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java, vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java, vassal-app/src/main/java/VASSAL/build/module/ServerConnection.java, vassal-app/src/main/java/VASSAL/build/module/map/MapShader.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/MapGrid.java, vassal-app/src/main/java/VASSAL/build/module/noteswindow/AddSecretNoteCommand.java, vassal-app/src/main/java/VASSAL/build/module/noteswindow/SetPrivateTextCommand.java, vassal-app/src/main/java/VASSAL/build/module/properties/IncrementProperty.java, vassal-app/src/main/java/VASSAL/build/module/properties/MutablePropertiesContainer.java, vassal-app/src/main/java/VASSAL/build/module/properties/MutableProperty.java, vassal-app/src/main/java/VASSAL/build/module/properties/PropertyChangerConfigurer.java, vassal-app/src/main/java/VASSAL/build/module/properties/PropertyPrompt.java, vassal-app/src/main/java/VASSAL/chat/ChatServerConnection.java, vassal-app/src/main/java/VASSAL/chat/ServerStatus.java, vassal-app/src/main/java/VASSAL/configure/ValidationReportDialog.java, vassal-app/src/main/java/VASSAL/counters/PieceAccess.java, vassal-app/src/main/java/VASSAL/counters/PieceFilter.java, vassal-app/src/main/java/VASSAL/counters/PieceFinder.java, vassal-app/src/main/java/VASSAL/counters/Properties.java, vassal-app/src/main/java/VASSAL/i18n/TranslatablePiece.java, vassal-app/src/main/java/VASSAL/tools/RecursionLimiter.java, vassal-app/src/main/java/VASSAL/tools/Sort.java, vassal-app/src/main/java/VASSAL/tools/UniqueIdManager.java, vassal-app/src/main/java/VASSAL/tools/image/ImageIOImageLoader.java
There are still lots of unnecessary `public` modifiers in almost all interfaces, even though everything is `public` by default in an interface, anything else would make no sense, an interface is a contract with the outside world and private/protected/package-visibility members don't belong in an interface.
=> Remove unnecessary modifiers from interfaces

vassal-app/src/main/java/VASSAL/tools/concurrent/ConcurrentSoftHashMap.java
@yanlyub Thanks for spotting this. I've never seen a bug report on it in all this time, so I suspect `get()` has rarely ever lost the race against clearing, but I'm happy to fix it.
=> Bug 13211: Fix ConcurrentSoftHashMap race

vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java
http://www.vassalengine.org/forum/viewtopic.php?f=2&t=12170
This was getting mentioned again in the forums, and I have a really lightweight solution I'd been using in a custom class. It seems like something that many module designers might like to do.
What it actually does: when something gets executed from a right-click menu of a piece, then IF the piece has dynamic properties for "ClickedX" and "ClickedY" they are updated with the map coordinates of the most recent click.
Use Case:
(1) I have a "big" piece (e.g. a picture of a province, or a battleship or whatever)
(2) I right click on it, and a context menu comes up
(3) Maybe what I pick from the menu is "Put a tank here"
(4) Piece that's processing the click can retrieve the map coordinates where the right-click took place, and use …
=> 13218 Allow a piece to find out its context menu click location

vassal-app/pom.xml
Oops. I deactivated these while setting up the spotbugs plugin.
=> Reactivate checkstyle and javadoc

vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Update the message when game can't be refreshed due to GamePeice Id issues that require the module to be edited and saved in 3.3.3 or later. Old message was refering to Vassal 3.0 from the time when GamePiece Id's was first introduced.
=> Update GameRefresher can't refresh message

vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
Fixes a bug reported by Charles Sutherland in which a rotation angle of 14.4 degrees (25 facings around the circle) causes the piece to get stuck because 359.9999999 != 0.0.
=> Bug 13234: Rotation gets stuck due to floating point error

vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
see start() method for a picture of how that happens
=> 10314 - NPE Fix - GameRefresher - dialog can be null if the dialog box is closed quickly while test is running

vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
All other paths in this trait have explicit NPE protect for "the piece might no longer be on a map", but this path had no protection, so it will NPE any time the piece gets GKC'ed off a map during its interactive free rotating thinger.
=> 2705 - NPE Fix - FreeRotator - protect from NPE if piece got moved off map by e.g. GKC.

vassal-app/src/main/java/VASSAL/preferences/PrefsEditor.java
The actual crash was in BooleanConfigurer but it was because of this.
=> 12888 - PrefsEditor - when cancelling, possibility of trying to set value of object to null (see also: BAD)

vassal-app/src/main/java/bsh/Primitive.java, vassal-app/src/main/java/bsh/bsh.jjt
Missed the implementation of the !~ beanshell function. The Parser recognises it, but Beanshell doesn't implement it.
=> Issue 13250 - Add implementation of Missing !~ Beanshell operator

vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/GridEditor.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java
lastClick got moved inside an only-left-mouse block. 
This appeared sometime after 3.2.17.
=> Bugfix13216 - Right-clicking to add Region to Irregular Grid was 100% broken in 3.3.2

vassal-app/src/main/java/VASSAL/tools/image/svg/SVGImageUtils.java, vassal-app/src/main/java/VASSAL/tools/image/svg/SVGRenderer.java, vassal-app/src/test/java/VASSAL/tools/image/svg/SVGImageUtilsTest.java
CSS 2.1 defined 96px = 1in, so we can now fix dimensions for all SVG which doesn't use font-relative sizes. This should prevent all reasonable SVG from throwing exceptions due to dimensions.
=> Bug 10414: SVG with non-px dimensions throws ImageIOException

vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
Previously there has been a "GlobalOptions" setting for center on opponents' moves, allowing module designers to essentially force this preference on players, even though it's not an appropriate preference for module designers to control.
This PR:
(1) Makes the preference for "Center on opponents' moves" always appear for every module
(2) Always honors the preference regardless of any previous module setting
(3) Removes the GlobalOptions attribute
=> 13276 - Center-on-opponents-moves now strictly a player preference

vassal-app/src/main/resources/logback.xml
If log levels DEBUG or TRACE are needed for development, a `/vassal-app/src/test/resources/logback.xml` can be added and will override the `logback.xml` for the production environment.
=> Do not log anything below log level INFO

vassal-app/src/main/java/VASSAL/configure/PropertiesWindow.java
We were rebuilding BasicModule (!) whenever we cancelled. Really just needed to copy the original data in the three text fields back over.
=> 3215 - Don't rebuild whole BasicModule after properties window cancel

vassal-app/src/main/java/VASSAL/build/module/Chatter.java, vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
Our new GlobalOptions attribute that controls the "Enable HTML" situation for a module isn't yet written into modules written by pre-3.3.3. So it wasn't displaying the preference in the Chat tab in that case, because GlobalOptions was never getting a "setAttribute" for that property, and displaying the preference depended on receiving the setAttribute (rathern than merely on the attribute currently having the right value). This now makes sure the preference gets created. Had to force the preference during Chatter (rather than during GlobalOptions addTo, where I first tried), because otherwise the preference ended up at a variable location on the tab.
=> (3.3.3) Be sure to show HTML-Enable pref even if reading a pre-3.3.3 module that doesn't have a GlobalOptions setting written in yet

vassal-app/src/main/java/VASSAL/build/module/Map.java
It's a module we don't have in our library and marked 1.0 so quite likely some brand new module he's making. It looks like it might be some thing where he doesn't actually *have* a map in the module yet or something like that. 
Anyway, the thinger that came up null was being protected from null elsewhere so it probably should be here.
=> 13200 - mainWindowDock could be null here

vassal-app/src/main/java/VASSAL/build/module/Map.java
So it turns out than when the module isn't fully "built" yet, the fabled "should be impossible" branch is actually the "normal" branch, and critical to actually getting the map set up to dock right! Argh!
So this should restore "actually having a map" behavior to Vassal. 
Anyway it's a LOT easier for ShouldDockIntoMainWindow to not know about any maps yet than we thought. As in it happens 100% of the times we load a module. Hahahahahahahahahahahahahaha.
=> ShouldDockIntoMainWindow - turns out 'impossible' branch is the 'normal' branch when building new module

vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java, vassal-app/src/main/java/VASSAL/tools/ScrollPane.java
This is actually pretty sweet, works a LOT better than I was expecting. And of course module designer has control of exactly what "zoom stops" are provided.
I don't think there's any need to provide a preference to e.g. turn this on and off, because realistically who does "ctrl + mousewheel" when they don't "mean it" anyway.
=> 13275 - Ctrl+MouseWheel will zoom in and out (Command + Mousewheel on Mac, of course)

vassal-app/src/main/java/VASSAL/build/module/Inventory.java, vassal-app/src/main/java/VASSAL/build/module/dice/BonesDiceServer.java, vassal-app/src/main/java/VASSAL/build/module/dice/DieServer.java, vassal-app/src/main/java/VASSAL/build/module/map/TextSaver.java, vassal-app/src/main/java/VASSAL/build/module/metadata/MetaDataFactory.java, vassal-app/src/main/java/VASSAL/chat/Compressor.java, vassal-app/src/main/java/VASSAL/chat/jabber/JabberClient.java, vassal-app/src/main/java/VASSAL/chat/node/Server.java, vassal-app/src/main/java/VASSAL/counters/Deck.java, vassal-app/src/main/java/VASSAL/launch/Launcher.java, vassal-app/src/main/java/VASSAL/launch/ModuleManager.java, vassal-app/src/main/java/VASSAL/launch/TileProgressPumpStateMachine.java, vassal-app/src/main/java/VASSAL/launch/TilingHandler.java, vassal-app/src/main/java/VASSAL/script/BeanShell.java, vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java, vassal-app/src/main/java/VASSAL/tools/BugUtils.java, vassal-app/src/main/java/VASSAL/tools/HTTPPostBuilder.java, vassal-app/src/main/java/VASSAL/tools/ZipUpdater.java, vassal-app/src/main/java/VASSAL/tools/icon/IconFactory.java, vassal-app/src/main/java/VASSAL/tools/image/svg/SVGImageUtils.java, vassal-app/src/main/java/VASSAL/tools/image/tilecache/TileUtils.java, vassal-app/src/main/java/VASSAL/tools/image/tilecache/ZipFileImageTiler.java, vassal-app/src/main/java/VASSAL/tools/imports/adc2/ADC2Module.java, vassal-app/src/main/java/VASSAL/tools/imports/adc2/SymbolSet.java, vassal-app/src/main/java/VASSAL/tools/logging/LoggedOutputStream.java, vassal-app/src/main/java/VASSAL/tools/version/GitProperties.java
Prevents the application from behaving differently on platforms with different default character encoding.
Explanation is here: https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#dm-reliance-on-default-encoding-dm-default-encoding
And also in the javadoc of the Java API calls that were changed, e.g. here: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/InputStreamReader.html, quote "The charset that it uses may be specified by name or may be given explicitly, or the platform's default charset may be accepted.".
=> 13325: Use explicit character set

vassal-app/src/main/java/VASSAL/build/module/Chatter.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/launch/PlayerWindow.java, vassal-app/src/main/java/VASSAL/tools/LaunchButton.java
Stop setting a baseline for LaunchButtons; what's reported by the underlying Swing machinery doesn't match up neatly when the labels are a mix of nothing, HTML, and HTML having multiple lines.
=> 13319: Multiline HTML labels breaks toolbar button alignment

vassal-app/src/main/java/VASSAL/launch/CreateModuleAction.java, vassal-app/src/main/java/VASSAL/launch/EditExtensionAction.java, vassal-app/src/main/java/VASSAL/launch/EditModuleAction.java, vassal-app/src/main/java/VASSAL/launch/NewExtensionAction.java, vassal-app/src/main/java/VASSAL/tools/ArchiveWriter.java
Up until now, if you make a new module, tell it to "save" or "save as", and type in "Name", you get a module named literally "Name", with no extension. 
This fix corrects that, adding ".vmod" to module saves if no fileext has been added, and ".vext" to a module extension missing a fileext.
=> 13326 - Saving a module will default to .VMOD, an extension to .VEXT

vassal-app/src/main/java/VASSAL/build/module/map/StackMetrics.java
There is evidence elsewhere in StackMetrics.java (see line 271) that Stacks sometimes exist "not on a map". And if one is *created* not-on-a map, as tried to happen here, this line will blow up. So I put in null protection for the map.
=> 12986 - Stack could be getting created not-on-a-map

vassal-app/src/main/java/VASSAL/counters/Footprint.java
I was auto-mapping new keystrokes when really it would be better to just leave them empty until someone wants them.
=> 3.4.0(!!) - Move Trails fix - shouldn't be forcing in new keystroke mappings

vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/preferences/Prefs.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Move Compatibility preferences to their own preference tab.
Also added a bit of text to the bug fix compatibility prefs to give an idea of what problems they solve and hopefully make it easier for users to find themselves.
=> 13098 - Move pure Compatibility preferences to their own tab

vassal-app/src/main/java/VASSAL/build/GpIdChecker.java
Markers are essentially constants and if we change one and run the Refresher, we expected the changed value to be put into the updated piece, not the old value copied from the old piece.
=> 13356 game refresher does not copy marker state

vassal-app/src/main/java/VASSAL/build/module/Map.java
This is the fix for the flare problem. 
I checked all other usages of Map.findZone(p) in Vassal (8) and all pass a throw-away point to findZone except for Decorator.setOldProperties() which had the potential to corrupt the setting of OldLocationName to based on Board co-ords instead of Map co-ords.
=> 13358 - Prevent units in Zones setting OldLocationName incorrectly

vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/map/Flare.java, vassal-app/src/main/java/VASSAL/command/FlareCommand.java, vassal-app/src/main/java/VASSAL/configure/FlareFormattedStringConfigurer.java, vassal-app/src/main/java/VASSAL/tools/SequenceEncoder.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
VASL has had a feature like this for a long time, and I actually had a random person come along and "insert it" into PoG as a custom class. Neither version is as good as This Awesome Feature (of course). It has also come up recently in the forums w/ various people asking for it. 
This version adds:
* Default of Alt+Click to send the ping. Ctrl+Click (an inherently terrible idea of course) is included because it was the VASL (and derivative custom class) keystroke, and so the usual bring-the-old-guys-along reasons. Possibly I could include things like other mouse buttons entirely (e.g. mousebuttons 3, 4, 5), though I want to think about it a bit since this is currently a module designer setting and not everybody would have those buttons (or want to be forced to use them). 
* Can configure …
=> 13296 - Flare feature for map (call opponent's attention to a location)

vassal-app/pom.xml
That prevents skipping them fromthe command line.
=> Don't hardcode non-skipping plugins, as that prevents skipping them

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java, vassal-app/src/main/java/VASSAL/build/module/metadata/ExtensionMetaData.java, vassal-app/src/main/java/VASSAL/build/module/metadata/MetaDataFactory.java, vassal-app/src/main/java/VASSAL/build/module/metadata/ModuleMetaData.java, vassal-app/src/main/java/VASSAL/tools/ArchiveWriter.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Now featuring a file extension for Extra Sanity!
* Looks for "buildFile" for all versions 3.4.999 and earlier. 
* Looks for "buildFile.xml" for all versions after that
* Writes buildFile.xml
* And then removes old "buildFile" instances lingering in the archive
=> 13363 - buildFile renamed to buildFile.xml for 3.5 and beyond

vassal-app/src/main/java/VASSAL/counters/Embellishment.java
The sequence langauge can't distinguish a single-element String array containing an empty string from a zero-element array, so in the case of Embellishment we have to help it out.
=> Bug 13373: Bad imageName array size

vassal-app/src/main/java/VASSAL/launch/StartUp.java
The GTK LaF's color picker is extremely reduced in functionality from the ones in other LaFs. Don't use it.
=> Improved color picker for GTK LaF

vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java, vassal-app/src/main/java/VASSAL/counters/DragBuffer.java
The "Undo bug" fix changed starting-a-drag behavior by no longer adding the actual Stack object to the DragBuffer (instead we are just holding the pieces that were inside it). And so now that is affecting the behavior at the other end when we are dropping the pieces.
The bad behavior we were seeing is pieces still seeing their "old stack" sitting there on the board "within merge range", and so they'd merge back into it and end up back in their same old location instead of at their new adjusted location.
So first part of this is a new special case is when we encounter a stack we might want to drop onto -- if DragBuffer already contains all current members of the potential target stack, then it is a stack we are in the process of emptying out, and we don't want to merge back into it. I've …
=> 3.4.2(!!) 13398 - Fix piece drag so that pieces can be moved a few pixels

vassal-app/src/main/java/VASSAL/counters/Pivot.java
I set this to 3.4.2 since it's both a "super simple and obvious fix", and since it was one where the user actually went to the trouble of filing a real Bug Tracker report and providing a module for repro. But it can be moved to 3.5 if we need to based on constraints.
Pivot has apparently been ignoring the GlobalOptions auto report setting ever since it was written, in _(checks notes)_ 2004!
=> 3.4.2 (?) - 13279 - Pivot was auto-reporting moves when auto-reporting is turned off.

vassal-app/src/main/java/VASSAL/build/module/Chatter.java, vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
The GlobalOptions default "Prompt" class has a "use user preference" option which is not a good one for "Enable HTML in Chat Log" to have. This change fixes it to ONLY accept "Always" or "Never" for the HTML-in-chat-log. 
Mostly cleanup because the preference thing was quasi-harmless, but it already caused confusion tonight so now it can DIE! DIE! DIE!
=> 3.4.2 (!) - Remove 'Preference' option from HTML-related stuff

vassal-app/src/main/java/VASSAL/build/module/Chatter.java, vassal-app/src/main/java/VASSAL/counters/PropertiesPieceFilter.java
Did some Big Boy Bisecting and we found a Broken Thing. Reverted it, and the problem went away. Yay! 
Marked with comments So We Will Know.
=> 3.4.2 (!!) - 13425 - MouseoverStackViewer legacy expression matching was broken by a code cleanup

vassal-app/src/main/java/VASSAL/configure/ExtensionTree.java
This doesn't look like it should fix the problem, but it does. With the changes to check isPopupTrigger(), all the proper ExtensionTree mouse handling is already there. The check for isEditable() should never have been added, you always want to create a popup. The popup contents and state are handled in ExtensionTree by over-riding the buildAction methods.
=> 13427 - Allow extensions to be edited on linux/Mac

vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Apparently PieceDefiner (ONLY) was still using crappy-non-browser help windows, while all other Help buttons and Help menus were using the real browser. So that means there's no Back Button in the browser help.
This should fix it up. 
I offer you the option of merging it into 3.4.3 "because one line". OR punt it to 3.5 "because not a new bug".
=> 3.4.3(?) PieceDefiner uses BrowserHelp

vassal-app/src/main/java/VASSAL/build/GameModule.java
Mark on the forums pointed out a case where Bad Module Data warnings with a < sign were being misinterpreted as HTML.
This patch will clear that up.
=> 3.4.3 - 13435 - Warnings with less-than sign being interpreted as HTML

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
Just don't have BasicLogger create a save string during its setup() method. It will create one anyway when a logfile is actually started.
=> 3.4.3 - 13342 - a much less scary fix version

vassal-app/src/main/java/VASSAL/Info.java, vassal-app/src/main/java/VASSAL/launch/ModuleManager.java, vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java, vassal-app/src/main/java/VASSAL/tools/BugDialog.java, vassal-app/src/main/java/VASSAL/tools/BugUtils.java
Up until now Vassal could only have one Module Manager running at the same time. Now, each VERSION of Vassal can only have one Module Manager running at the same time. 
This should help people who need/want to run multiple versions of Vassal because of different modules (and module maintainers) having different requirements.
=> 3.4.3 - 13436 - Module Managers for multiple versions of VASSAL can coexist

bootstrap.sh
Java 14 will not receive support anymore.
This fixes https://bugs.openjdk.java.net/browse/JDK-8238575 (Drag on HiDPI screens), among other things.
=> 13452: Bundle Java 15

developers-guide/developers-guide.adoc, pom.xml, release-prepare/pom.xml
```
zorro@xorro:~/dev/vassal$ ll release-prepare/target/lib/licenses/
total 208K
drwxrwxr-x 2 zorro zorro 4,0K Sep 24 01:13  ./
drwxrwxr-x 3 zorro zorro 4,0K Sep 24 01:13  ../
-rw-rw-r-- 1 zorro zorro  12K Sep 24 01:13 'apache license, version 2.0 - license-2.0.txt'
-rw-rw-r-- 1 zorro zorro  31K Sep 24 01:13 'bsd - bsd.license.html'
-rw-rw-r-- 1 zorro zorro  13K Sep 24 01:13 'eclipse public license - v 1.0 - epl-v10.html'
-rw-rw-r-- 1 zorro zorro  22K Sep 24 01:13 'gnu lesser general public license - lesser.html'
-rw-rw-r-- 1 zorro zorro  39K Sep 24 01:13 'gnu lesser general public license - lgpl-2.1.html'
-rw-rw-r-- 1 zorro zorro  39K Sep 24 01:13 'gnu lesser general public license, version 2.1 - lgpl-2.1.html'
-rw-rw-r-- 1 zorro zorro  31K Sep 24 01:13 'mit license - mit-license.html' …
```
=> Add License Maven Plugin for downloading licenses of dependencies

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
3.5 has a much better & more comprehensible "reminder-to-start-logfile" flow. 
At the time I did it, I didn't realize quite how big of an issue this was in the community (or I'd have done it for 3.4 back when there was time), but ALSO because of that lack of realization, I didn't default the preference to on (and I just used the old preference which everyone already HAD defaulted to off anyway). 
So now this defaults those logfile preferences to "on", and uses a new key so that with 3.5 it will start "defaulted on" for everyone including players upgrading. And it has a "don't ask again" button on the box so the people that don't want it will just click that and everything will be fine.
But for all the PBEM people it will now remind them not only when they finish a log file, but ALSO when …
=> 3.5 - Default logfile prompt to on

vassal-app/src/main/java/VASSAL/configure/AutoConfigurer.java, vassal-app/src/main/java/VASSAL/configure/TranslatableStringEnum.java, vassal-app/src/main/java/VASSAL/configure/TranslatingStringEnumConfigurer.java
Default is still to pass "keys". Adding extra constructor boolean parameter allows telling it we are sending pre-translated strings so it shouldn't run Resources.get() again on them.
This should give us the flexibility to navigate past situations where translated strings are available but "keys" are not.
=> 3.5 - Allow full-translated strings into TranslatedStringEnum/TranslatingStringEnumConfigurer family as CTOR option

vassal-app/src/main/java/VASSAL/command/SetPersistentPropertyCommand.java, vassal-app/src/test/java/VASSAL/command/SetPersistentPropertyCommandTest.java
I'm not sure why it thinks I have replaced the whole SetPersistentPropertyCommand file when I just changed one line, but the result is correct.
=> 3.4.4 Bug 13454 - Fix ClassCastException in SetPersistentPropertyCommand.execute()

vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java, vassal-app/src/test/java/VASSAL/script/expression/PropertyMatchExpressionTest.java
Caused by overly aggressive fix for bug 13381.
Replace Float conversion but check for and exclude numeric literals first.
Added Regression test.
=> 3.4.4-13458-Allow floats to be compared in Beanshell. (Regression). 

vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
Up until now if you backspaced to the beginning of a namedhotkeyconfigurer it would inappropriately move focus to another field. This fixes it.
=> 3.5 - 13486 - Backspacing in NamedHotKeyConfigurer will no longer shift focus

vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Fixes the following issue:
When a saved game is loaded "normally" (through the file menu), the most recent filename loaded is remembered as the default for the next save/load operation.
However when the initial file is loaded via the Wizard, this information is lost and so attempting to save the game leaves you with no "default" and possibly not even in the right directory.
=> 3.5 - 13495 - loading saved game from wizard remembers default name appropriately

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Here's a quickie life-enhancer that should probably go in 3.5 (it is simple as rocks).
Exposes the following properties to the module:
$ModuleVersion$
$ModuleName$
$ModuleDescription$
$ModuleOther1$
$ModuleOther2$
$VassalVersionCreated$
$VassalVersionRunning$
These can now be accessed from anywhere (i.e. Beanshell expressions, $..$ text fields, and the like).
I added the two Other fields to provide a place where module designers can stash information for the module that is NOT saved as part of the saved game (I have a use for this - I imagine others will find uses as well)
=> 3.5 - 13494 - Expose versions and module strings to module as properties

vassal-app/src/main/java/VASSAL/build/module/Chatter.java, vassal-app/src/main/java/VASSAL/build/widget/HtmlChart.java, vassal-app/src/main/java/VASSAL/tools/swing/DataArchiveHTMLEditorKit.java, vassal-app/src/main/java/VASSAL/tools/swing/HTMLWindowHelper.java
Our old HTMLEditorKit replacement doesn't handle attributes properly; the JDK's HTMLEditorKit holds open the module file with no way to close it properly. This fixes both.
=> 13467, 13469: HTML img elements refering to images in module hold it open

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
I'm not sure what, if anything, the old attempted fix for this accomplished (perhaps something...) but in any event it did not touch the issue for stacks assigned a Grid Location on an "<any>" owning board at all. It was still setting the final position based on the "top board in the list" rather than based on the board picked by the player.
This PR hopefully fixes that -- I mean, it DOES "apparently fix" it for me, but please check the code carefully.
The earlier stuff in 'setAttribute()' **doesn't actually run** during the "start new game" sequence when a player picks a board -- it has already run during the load of the module in the first place. So that whole set of code kind of scares me but in any event I didn't have to interact with it to fix this.
=> 3.4.6 - 12576 and 13456 - setup stack grid locations for 'any' board stacks

vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java, vassal-app/src/main/java/VASSAL/counters/PieceFinder.java
There has been a thread on the forums (http://www.vassalengine.org/forum/viewtopic.php?f=3&t=11438) where they are complaining about it doing a band-select when you drag things off a deck. 
For some reason this problem seems "worse" on Macs than on PC, but I am able to see at least some of the problem on PC. 
In any event, I this this PR should fix the problem. Doesn't allow band-selects to start on top of a deck.
=> 3.4.6 - 13505 - Deck band select fix

vassal-app/src/main/java/VASSAL/build/GameModule.java
Switch to "ServerSelected" for the selected game server pref name to avoid having older versions read values they can't process.
=> Use ServerSelected instead of ServerImpl for selected game server

vassal-app/src/main/java/VASSAL/tools/imageop/AbstractTileOpImpl.java
Call getSize() to ensure that size is set properly.
=> 13508: NPE in GamePieceOpImpl.getTileIndices()

vassal-app/src/main/java/VASSAL/tools/Mp3AudioClip.java
Refactored error handling for MP3s. IOExceptions are not bugs.
=> 13547: Don't raise a bug dialog on failure to read an MP3

vassal-app/src/main/java/VASSAL/build/module/map/LayeredPieceCollection.java, vassal-app/src/main/java/VASSAL/counters/Stack.java
Stacks are now soulbound to the layer of the first gamepiece added to them, so that they will properly restore themselves to that layer when loading savegame files.
=> 3.4.8 - 13577 - Stacks properly restore their visual 'layer' level when saved/restored

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java, vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java, vassal-app/src/main/java/VASSAL/preferences/Prefs.java
Separate PR because I did some very minor code-refactoring (e.g. reordering the preference objects into coherent groups by tab). Nothing that should change the effect of the code, but "worth checking".
=> 3.5 - Javadoc and 'mild refactor' of GlobalOptions

vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java, vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java, vassal-app/src/main/java/VASSAL/build/module/map/LOS_Thread.java, vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
Earlier during 3.5 process I made AbstractToolbarItem to handle the common case of "Configurables that run from a Toolbar launch button". I left MassKeyCommand out because we had that ginormous GKC project going at the time -- so now that we got that all merged I have come back to clean up this little detail.
=> 3.5 - Belatedly make GKC's use AbstractToolbarItem now that we've come to a more stable point.

vassal-app/src/main/java/VASSAL/command/MovePiece.java
Bug seems likely to have involved pieces being moved/deleted simultaneously in an online multiplayer game.
=> 13631 - somebody yanks a piece away

vassal-app/src/main/java/VASSAL/counters/Labeler.java, vassal-app/src/main/java/VASSAL/tools/imageop/AbstractTiledOpImpl.java, vassal-app/src/main/java/VASSAL/tools/imageop/GamePieceOpImpl.java, vassal-app/src/main/java/VASSAL/tools/imageop/OrthoRotateOpBitmapImpl.java
When fixSize() and fixTileSize() are not atomic (in this case, that means they do more than assign the correct value to one variable as a single assignment---a single assignment need not be synchronized because size computation is idempotent, so it doesn't matter which thread wins the race), then the part containing the computation must be synchronized.
=> 13677, 13679 - Ensure AbstractTiledOpImpl.fixTileSize() is atomic

vassal-app/src/main/java/VASSAL/build/module/Map.java
Set the minimum size of the top and bottom components in the main split pane later, in case module custom code replaces one of them.
=> Set main split pane components minimum size later

vassal-app/src/main/java/VASSAL/counters/Embellishment.java
Rewrite changed order that Listeners where firing causing fields to be updated in incorrect order.
=> 3.5 13782 Layer losing track of Suffix/Prefix setting on layers

vassal-app/src/main/java/VASSAL/build/module/GameState.java
I noticed that when I load a new logfile in (planning to replay it), I'm getting *immediately* prompted to start a new logfile. Which seems wrong -- because since I'm replaying one I will get a prompt at the END of the replay. 
So this little fix patches that.
If it wanted to get cherrypicked to 3.4.12 that could happen to, or I could probably re-poot this PR to that.
=> 13808 - Don't prompt to create new logfile before current one is done

vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
This should not be necessary given that we create it in StandarConfig, but somehow the directory isn't there for Windows users occasionally.
=> 13820 - Ensure that the temp dir extists before trying to write to it

vassal-app/src/main/java/VASSAL/Info.java, vassal-app/src/main/java/VASSAL/build/module/InternetDiceButton.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java, vassal-app/src/main/java/VASSAL/build/module/PrivateMap.java, vassal-app/src/main/java/VASSAL/build/module/RandomTextButton.java, vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java, vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java, vassal-app/src/main/java/VASSAL/chat/PrivateChatter.java, vassal-app/src/main/java/VASSAL/chat/ui/ChatServerControls.java, vassal-app/src/main/java/VASSAL/configure/ModuleUpdaterDialog.java, vassal-app/src/main/java/VASSAL/launch/EditorWindow.java, vassal-app/src/main/java/VASSAL/launch/ExtensionEditorWindow.java, vassal-app/src/main/java/VASSAL/launch/ModuleEditorWindow.java, vassal-app/src/main/java/VASSAL/launch/PlayerWindow.java, vassal-app/src/main/java/VASSAL/search/HTMLImageFinder.java, vassal-app/src/main/java/VASSAL/tools/DataArchive.java, vassal-app/src/main/java/VASSAL/tools/JarArchive.java, vassal-app/src/main/java/VASSAL/tools/imports/adc2/ADC2Module.java, vassal-app/src/main/java/VASSAL/tools/imports/adc2/MapBoard.java, vassal-app/src/main/java/VASSAL/tools/version/VassalVersionTokenizer.java, vassal-app/src/main/java/VASSAL/tools/version/VersionTokenizer.java, vassal-app/src/test/java/VASSAL/chat/CompressorTest.java, vassal-app/src/test/java/VASSAL/tools/io/RereadableInputStreamTest.java, vassal-app/src/test/java/VASSAL/tools/version/VassalVersionTokenizerTest.java, vassal-app/src/test/resources/clirr-ignored-differences.xml
Deprecated elements marked "forRemoval" have deprecation warnings of type "removal", not "deprecation". Elements which are themselves deprecated which also refer to deprecated-for-removal elements need to have the "removal" warnings on them suppressed explicitly.
=> Deprecation cleanup

vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/GridOp.java
=> 13915 - GridOp.TileOp should include its parent GridOp in its hash rather than its parent's source

vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Found a code path where the saved-game name doesn't get added to the app title.
=> 13959 - 3.5.1 - Wizard should add loaded-file name to app window title

vassal-app/src/main/java/VASSAL/tools/BugUtils.java
There is no GameModule when running the Module Manager. Fixed NPE in ABR construction.
=> 13984 - NPE when constructing ABRs from the Module Manager

vassal-app/src/main/java/VASSAL/counters/Immobilized.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Alt used to be the only allowable modifier key.
=> 3.5.1 - 13977 - Alt+Shift now a configurable option for band-selectability of does-not-stack pieces.

vassal-app/src/main/java/VASSAL/counters/Embellishment.java
Layers which have no image may have a null in imageName array.
=> 13992 - Don't add nulls to used images list. Layers which have no image may

vassal-app/src/main/java/VASSAL/build/module/Map.java
Check that splitPane is null---i.e., we have not yet nicked the components from mainWindowDock---in modules where mainWindowDock is used by custom code.
=> 13944 - Ensure that deprecated mainWindowDock is fiddled on first pass only

vassal-app/src/main/java/VASSAL/launch/Editor.java, vassal-app/src/main/java/VASSAL/launch/Player.java
Technically, this should never happen as the MM cleans up its list on startup, but people can move, rename or overwrite modules under the MM while it is running.
=> 13988 Show Invalid module dialog if trying to load or edit an invalid or missing module from the MM

vassal-app/src/main/java/VASSAL/counters/Marker.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
=> 14059 - better piece definer descriptions of Marker traits

vassal-app/src/main/java/VASSAL/build/module/GlobalKeyCommand.java
The little tag probably got lost during some complex merge back when 3.5 was pre-release and large swathes of things were getting changed.
=> 3.5.4 - 14136 - Module level GKCs were not honoring fast match

vassal-app/src/main/java/VASSAL/counters/Delete.java
This one that should have been done ages ago. Delete is really a 'Move' type trait, so the oldxxxx Properties need to be set prior to deleting the counter. There have been many complaints and questions about correctly reporting the location of deleted counters over the years.
Currently, it is impossible to report the location a counter is being deleted from if it has not been moved since being added to the map.
=> 14139 - Delete trait to set old... properties before deleting unit

bootstrap.sh
It was updated last month, and the download URL now refers to 3.13
=> Change launch4j version to 3.13

vassal-app/src/main/java/VASSAL/build/widget/TabWidget.java
When module designers put html (e.g. "<html><b>Bold Boy</b></html>") in the text of the widgets for chart windows, Swing seems to do some grotesque things (losing track of the ordering of the list of tabs). Refreshing them "every time you do anything" seems to be a workaround. Note that when refreshing them you have to kind of "unset" and then "set" their title otherwise Swing has some "oh look it's the same as before so I will do nothing" code that prevents the desired relief.
=> 14245 - Works around bug in JTabbedPane

vassal-app/src/main/java/VASSAL/build/module/properties/SumProperties.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Existing functionality only allows $sum(somePropertyName) and then sums the property, which can be useful but is unfortunately infuriating when you only want a sum of how many pieces met the qualifications to be displayed, because then you have to go add a property to every possible piece "StupidProperty" and set its value to "1". So that you can sum it. 
Anyway this fixes that.
=> 3.5.4 - 14217 - $countPieces$ to sum all pieces without having to create a property

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java
I had removed a "gameLoadingInForeground" flag that I thought *I* had put in, since it was interfering with using the LoadGameInForeground method. But it turns out @claudiociardelli had put it in for the Refresh Predefined Setups tool -- so in other words I broke that. This restores the semaphore that should get Refresh Predefined Setups back to how it previously behaved while letting LoadGameInForeground still work for me -- by slightly changing where the semaphore is activated.
=> Fix the Refresh Predefined Setups flow that I broke

vassal-app/src/main/java/VASSAL/configure/StringArrayConfigurer.java
There was a race condition when adding/removing/moving an entry while also typing. A hanging PropertyChangeListener could fire after it's owning ListEntry had been removed from the array of known ListEntries before being rebuilt.
=> 14069 ArrayOutOfBounds exception in StringArrayConfigurer

vassal-app/src/main/java/VASSAL/tools/KeyStrokeListener.java
This prevents later listeners from unregistering earlier ones.
=> 13145 - Allow the inner listeners of KeyStrokeListeners to be chained

vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
This should be "looked at carefully by experts". 
REALLY I wish the whole "offset" thing didn't exist -- it seems to bounce "p" back and forth between values in a maybe-not-very-understandable way. 
Like couldn't we just use **dragging.getPosition()** for each unit coming through the loop as the "p" for that unit? Maybe I'm missing something important that bouncing around with offset does?
Anyway removing the "offset == null" **seems** to fix 13796. Only adding making the offset when offset == null seemed to be the reason that only the "first stack it started making" got created correctly.
=> 13796 - Fix problem with multiple stacks dragged to a snap-to map

vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
Try getting a canonical path before calling File.listFiles(), since that seems to have a problem on MacOS when the path is a symlink.
=> 14163 - NPE due to File.listFiles() returning null for symlnks on Macs

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java
"End logging" managed to throw an exception in the wild. On analysis the conditions for starting/stopping logs looked a little delicate & sensitive, and subject to being called at "odd times". So now it will be safer in several ways.
=> 3.5.6 - 14370 - safer behavior of log startup/ending

vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/counters/ReportState.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/ReportChanges.adoc
Here's something I've always wanted (and need!) -- a way to ensure certain critical report messages can override the "suppress individual reports" checkbox of a GKC. My use case is for "Warning! You probably just broke the rules!" messages -- allowing those to "pop through" the GKC suppression which otherwise needs to suppress a whole lot of more routine messages.
=> 3.6 - 14358 - ReportState checkbox overrides GKC suppression of individual reports

vassal-app/src/main/java/VASSAL/launch/Launcher.java, vassal-app/src/main/java/VASSAL/launch/StartUp.java, vassal-app/src/main/java/VASSAL/preferences/Prefs.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Allows the default font for VASSAL and the Editor to be a different size, via General Preferences tab.
=> 3.6 - Default Font Size change

vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java
http://www.vassalengine.org/forum/viewtopic.php?f=4&t=13014
=> 3.6 - 14278 - Increased # of default zoom levels (since modern monitors mean people use vassal at a wider variety of resolutions)

vassal-doc/pom.xml, vassal-doc/src/main/designerguide/designerguide.adoc, vassal-doc/src/main/userguide/userguide.adoc
Just checked the configuration and found some things to improve.
Feel free to ignore this PR this don't make sense to your current approach.
* Fix html file extension override
`filetype` attribute does not apply to file conversion, you need to use `outfilesuffix`.
If you don't want to change the file extension, just remove the attribute.
* Simplify `optimize` attr
This attribute does not need any value. Also if it's causinf trouble due to the issue with asciidoctor-pdf, you can just run the command with `-Dasciidoctor.attributes=!optimize` to unset it from the command line. You can also add this to the properties section in settings.xml to avoid typing it any time.
Also saw, you are composing the user guide. You may be interested to use `:leveloffset: +1` …
=> Small fixes to docs

vassal-doc/src/main/readme-referencemanual/ReferenceManual/MassPieceLoader.adoc
14409 MassPieceUploader - mention in help that filenames cannot contain dot + suffix separator cannot be dot
=> MassPieceUploader adoc clarification

vassal-app/src/main/java/VASSAL/counters/Embellishment.java
I propose that we set the default for the "Always Active" checkbox on brand new Layer traits to be "true". 
My reasoning:
(1) Having it default to "false" leads to confusion when beginner (or merely hasty) module designers make a layer trait and it doesn't "show up" when they look at their piece in the definer / palette / module.
(2) "Modern" modules are more likely to have layers "follow expression value" than be "activated" by keystrokes
(3) I have had to remember to manually check this box in 100% of the Layers in 100% of the modules I have ever worked on.
=> 14423 - True is a better always-active default for brand new Layer traits

vassal-app/src/main/java/VASSAL/counters/Mat.java, vassal-app/src/main/java/VASSAL/counters/MatCargo.java, vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Some cosmetic touchups I noticed needing to be done when I started using Mats:
(1) Was defaulting the Mat *description* rather than the *name* to be "Mat". Have swapped.
(2) Was defaulting keep-facing-with-mat to "false", have swapped to "true".
(3) There were buildDescription shenanigans when displaying the name of the the potential new trait in PieceDefiner.
=> Mat Touchups - proper default names, proper default checkbox, and don't put spurious description in piece definer's version of the name

vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
Mark found a text alignment problem when "extra space between" was being selected, and I discovered a spurious "additional add" of the value. This should correct it.
=> 14468 - CounterDetailViewer fix

vassal-app/src/main/java/VASSAL/counters/Labeler.java
The Labeler's recursion limit protection appears to have been misimplemented.
=> 14261 - fix infinite loop protection for Labeler

vassal-app/src/main/java/VASSAL/counters/Obscurable.java
Check Invisible trait as well and it was already doing the correct thing.
=> 2623 - Can Rotate trait respects mask image when sides change

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java, vassal-app/src/main/java/VASSAL/build/module/ObscurableOptions.java, vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java, vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java, vassal-app/src/main/java/VASSAL/build/module/chessclockcontrol/ChessClock.java, vassal-app/src/main/java/VASSAL/build/module/map/TextSaver.java, vassal-app/src/main/java/VASSAL/build/module/noteswindow/PrivateNotesController.java, vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNotesController.java, vassal-app/src/main/java/VASSAL/command/MoveTracker.java, vassal-app/src/main/java/VASSAL/counters/PlayerAccess.java, vassal-app/src/main/java/VASSAL/counters/Restricted.java, vassal-app/src/main/java/VASSAL/counters/Translate.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
The _main_ problem this is intended to solve is that when people have been using a default password (whether "" or "Username's Password") then switch to using an "actual" password (i.e. that they've chosen themselves), they have been losing access to these old saved games. 
A _secondary_ problem that is also solved (or at least addressed) is that now "" will always be the default assigned password, no more "Username's Password". Which of course may produce more players with blank passwords discovering that a blank password isn't very useful for claiming a side in a multiplayer game, but that's probably at least "more transparent" than what's going on now.
The _mechanism_ I've chosen is to intervene primarily at the point a player claims an existing side in an existing game. 
* If, as will …
=> Password UX improvements (aka "Just shoot me now")

vassal-app/src/main/java/VASSAL/counters/NonRectangular.java
This will make non-rectangular traits in 3.6 modules more compatible with 3.5, assuming the module designer hasn't actually implemented any 3.6 features (so merely *running* 3.6 won't be incompatible with 3.5)
=> 3.6 - Stay compatible with 3.5 non-rectangular traits as long as possible

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/java/VASSAL/launch/EditorWindow.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Can now "duplicate" an item in the editor by hitting Ctrl+D (similar to keys for cut, paste, etc)
=> 14586 - Editor Duplicate Key

vassal-app/src/main/java/VASSAL/build/GameModule.java
I'm finding the force-re-add of Game Piece Image Definitions to be quite cluttery and annoying. 
We only added this for 3.6 so no ticket number. 
In theory we could allow the manual re-adding of these, although with them being so incredibly obsolete these days it doesn't particularly seem worth it?
=> Don't force Game Piece Image Definitions

vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java
"This PR is its own ticket"
When you edit an IrregularGrid, it used to just start its little editor view at the upper left corner of the map. Which is of course annoying when the map is 8000x8000 and your grid/zone is in the lower right or whatever.
So this now attempts to make an at least vaguely sensible centering as the starting point:
(a) If the IrregularGrid has any Regions in it, then the regions are used as a place to scroll the map
(b) If the IrregularGrid has NO Regions, but is part of a Zone, then the Zone shape is used.
Tested this in both cases and it produces pretty reasonably sensible starting points. Definitely open to ways it could be even smarter.
=> 10277 - When editing an IrregularGrid, start the map view somewhere near the grid or its parent Zone

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java, vassal-doc/src/main/designerguide/maps-and-boards.adoc
So I've got these cards that "tuck underneath the map", and it's working perfectly w/ a CalculatedProperty to tell them whether to use their "top half is transparent" version of the image.
However when one "rolled over" the card for CounterDetailViewer, it of course displays the ugly "half empty field" version of the image in the Mouseover box. 
(Oh and by the way this is NOT the first time this same issue has come up for me making a module - I've run into similar situations with previous modules and just never got around to making this change)
So this PR makes there be a property you can check if you're currently drawing the CounterDetailViewer, and results in the "correct result" below:
=> 10276 Expose property if we're currently drawing Counter Detail Viewer

vassal-app/src/main/java/VASSAL/counters/MatCargo.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/MatCargo.adoc
I have cards that I need to "tuck halfway under mats". Obviously making the user get the precise one-pixel center point just onto the mat as opposed to just-not-on-it would be "Bad UX". 
So here's a way to add some extra detection points to the MatCargo when it goes looking for its next mat. 
A bit kludgey but (a) it should solve 99% of conceivable issues in this depatment, (b) I don't have the math to do better, and (c) doing *much* better would presumably require rewriting PieceFinder.
=> 10273 Mat Cargo can be set to detect mats way from their exact center

vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/Region.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Right new every time you make a new region it gets auto-named "New Region" which means you have to first delete all of that text every single time. So I've changed it to a blank string which seems a lot easier-to-use.
=> 10272 Don't auto-name new regions a long string

vassal-app/src/main/java/VASSAL/counters/BasicPiece.java, vassal-app/src/main/java/VASSAL/counters/Decorator.java, vassal-app/src/main/java/VASSAL/counters/Mat.java, vassal-app/src/main/java/VASSAL/counters/MatCargo.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/MatCargo.adoc
Mat Cargo now track an OldMat and OldMatID, corresponding with CurrentMat and CurrentMatID.
This also fixes some bugs I found with moving a piece from one mat to another (apparently my testing was mostly moving onto and off of mats, less transferring between mats). Hooray for actually making a module in parallel with the new feature :)
"This PR is its own ticket"
=> Properties for OldMat, OldMatID, etc.

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Minor touchup of the "Duplicate" action that I believe is already a "new with 3.6 feature"
PREVIOUSLY - if you duplicated an item and accepted/saved from the configurer that appeared, the OLD item (the one you'd duplicated) would stay selected. This got a bit confusing to me, because when you'd just been editing the NEW item it seemed like the new item would be the one selected (and so I'd sometimes end up next editing a child of the OLD item by accident)
NOW - if you duplicate an item and save/accept from the configurer, the NEW item becomes selected (if you cancel, the old item stays selected since the new item ends up not actually being created)
Not sure this even needs a new entry in the change list (since it's just a touchup of a new feature)
=> 10297 - EDITOR - After duplicating an item in the Editor and saving it, select the duplicate

vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/HexGridNumbering.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/RegularGridNumbering.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/SquareGridNumbering.java
Set a maximum hex size of 100 px wide when drawing grid visualiser to keep it usable with large hex sizes.
Closing #6130
=> 6130 Grid Numbering dialog can appear blank when grid size is very large

vassal-app/src/main/java/VASSAL/launch/TilingHandler.java, vassal-app/src/main/java/VASSAL/tools/image/tilecache/ZipFileImageTiler.java
ZipFileImageTiler now exits with 2 on an OutOfMemoryError, and TilingHandler responds by doubling the max heap and trying again, for a max of two retries.
=> Double max heap and retry when image tiler runs out of memory

vassal-app/src/main/java/VASSAL/launch/AbstractLaunchAction.java, vassal-app/src/main/java/VASSAL/preferences/Prefs.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
This provides the solution to poor rendering performance on M1 Macs, discovered in a comment here:
https://youtrack.jetbrains.com/issue/JBR-3237
=> Add option to disable OpenGL FBOs on Macs

vassal-app/src/main/resources/removed
Fixed typos. Inner classes need to be indicated by $.
=> Fixed typos in removed list

vassal-app/src/main/java/VASSAL/build/module/properties/EnumeratedPropertyPrompt.java, vassal-app/src/test/resources/clirr-ignored-differences.xml
This was caused by addition of AuditTrails exposing a shadowed field. 3.6 bug only.
=> 10375 NPE in EnumeratedPropertyPrompt

vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
The Deck Name is lost in Return to Deck traits when a module is loaded into Vassal (edit or play) if the RtD trait references a Deck in a Map that has not been built when the piece is built. e.g. a piece in an at-start stack references a Deck in a later Map.
=> 10357 Deck Name can be lost in 3.6

vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceImage.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Newly created GPI's will be forced to be a valid file name containing only 09,a-z,A-Z and _ and ending in .png.
Not much can be done about filenames of existing GPI's as other components will be referencing them. However, if an existing GPI has a valid filename, or is changed to gave a valid filename, then valid filenames will be enforced for that GPI from then on.
=> 10226 Force Game Piece Image names to be valid png filenames

vassal-app/src/main/java/VASSAL/build/BadDataReport.java, vassal-app/src/main/java/VASSAL/counters/Embellishment.java, vassal-app/src/main/java/VASSAL/counters/PlaySound.java, vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java, vassal-app/src/main/java/VASSAL/counters/SendToLocation.java, vassal-app/src/main/java/VASSAL/script/expression/AuditableException.java, vassal-app/src/main/java/VASSAL/tools/FormattedString.java, vassal-app/src/test/resources/clirr-ignored-differences.xml
Show a complete audit trail where an expression does not fail, but produces an invalid value in the context of the command being executed. e.g. returning a non-number for an x co-ord.
=> Trait AuditTrail Improvements for beta-2

vassal-app/src/main/java/VASSAL/preferences/Prefs.java
Both `NoSuchFileException` and `FileNotFoundException` can occur. They both need to be caught for the "new prefs file" case.
=> Catch FileNotFoundException when reading prefs files

vassal-app/src/main/java/VASSAL/build/module/GameState.java
Clear the pieces in the current game state completely before loading a new log file on top.
=> 10405 Fix issue with Delete trait failing after load log file

vassal-app/src/main/java/VASSAL/counters/Decorator.java
OLD_MAT (and OLD_MAT_ID) were using a different mat name string than CURRENT_MAT and CURRENT_MAT_ID. So this fixes them to use the same mat name.
=> 10449 - Make OLD_MAT use same format name as CURRENT_MAT"

vassal-app/src/main/java/VASSAL/Info.java, vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/launch/AbstractLaunchAction.java, vassal-app/src/main/java/VASSAL/launch/Config.java, vassal-app/src/main/java/VASSAL/launch/DummyConfig.java, vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java, vassal-app/src/main/java/VASSAL/launch/StandardConfig.java
The latter causes problems for people with a settings directory which
lives on a network share.
=> Store the tile cache in %LOCALAPPDATA% instead of %APPDATA% on Windows.

vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/PieceWindow.adoc
This allows the module designer to tweak the default pixel width at which the auto-docked Piece Window initially attempts to open (because apart from that it uses total Java black magic and there is no way to control it from the module).
=> 10454 - Game Piece Palette allows setting of default width for "docked" Game Piece Palette

vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java, vassal-app/src/main/java/VASSAL/counters/Deselect.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Deselect.adoc
I've discovered a few more UX cases for Mats that led me to want to improve the select/deselect options.
I've improved the existing Deselect trait to allow three "modes" of Deselection:
(1) Deselect this piece (default & what the trait formerly only did)
(2) Deselect ALL pieces
(3) Select ONLY this piece
Also double clicking a Mat can be used to ditch selection of cargo items.
=> 10484 - Deselect trait improvements and double-click Mat

vassal-app/src/main/java/VASSAL/tools/deprecation/RemovalAndDeprecationChecker.java
Means deprecation checker doesn't run when you launch Module Manager from the debugger and then launch/edit a module, but better than crashing and not being able to use Module Manager in that context
=> 10495 - Allow module manager to launch things from the debugger w/o deprecation manager crashing

vassal-app/src/main/java/VASSAL/counters/Obscurable.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mask.adoc
In a "Mask" trait, the current "Inset" option doesn't work well (at least for me) because it draws the "masked back" over top of 1/4 of the "real" image, meaning that if you need to be able to read the card text of the real image, you can't. 
So I have added a second inset option, which instead uses the "masked back" as the "behind part" and puts the "real image" as the inset, and at a larger amount of space.
=> 10486 Better obscurable option for insetting

dist/linux/VASSAL.sh, vassal-app/src/main/java/VASSAL/launch/JavaVersionChecker.java
lUse an empty class with a main() to check if the java on the path can load our class files; if not, complain. Should be more reliable than
trying to parse `java -version`.
=> More robust Java version check for Linux

vassal-app/src/main/java/VASSAL/build/module/GameState.java
This should do the ight thing in odd situations where maps share an id (possibly due to
editing).
Fixes #8949.
=> Check maps by id rather than by strict equality

vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java, vassal-app/src/main/java/VASSAL/counters/GlobalCommandTarget.java, vassal-app/src/test/resources/clirr-ignored-differences.xml
Previously having a fast match field set to
`$Side$ Lords Area`
worked right, but
`{"$Side$" + " Lords Area"}`
did not.
This "Weird Trick" seems to make it all work right.
=> 10547 Improve fast match expressions interaction w/ $...$ and Beanshell

vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
Found a fun little bug/thing -- when we Place Marker (trait) a new cargo piece on a mat, we assign it to the mat. 
However when you later move it off of the mat (or wherever), it starts with an OldMat (OLD_MAT) property set to "" instead of the Mat you're moving it from. 
So I've made the initial creation of a marker by PlaceMarker account for this by setting the Old Mat properties.
Really it seems like we should perhaps be doing a full "putOldProperties" here (since the same issues will apply to markers being created for the first time by PlaceMarker). However I didn't go that far at least for the present because I wasn't sure what kind of "Old Module Issues" might be created by that -- whereas since Mat stuff is new we can have it work right from the get-go.
=> 10543 - Place Marker trait properly initializes OldMat properties

vassal-app/src/main/java/VASSAL/configure/GlobalCommandTargetConfigurer.java, vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java, vassal-app/src/main/java/VASSAL/counters/GlobalCommandTarget.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/FastMatch.adoc
Global Key Commands now include a fast-match location option of "Current Mat".
If the current piece is either a Mat, or a MatCargo piece that is currently _on_ a Mat, then the Mat followed by each of its MatCargo  pieces are checked.
=> 10558 - "Current Mat" Fast-Match option

vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Presently the Paste button in the PieceDefiner remains greyed out at inappropriate times, if you're cut-and-pasting from one PieceDefiner window into an empty one. 
Since the Paste function is already protected against null clipboards, it doesn't really need "enabled" protection -- so rather than try to trace down esoteric ways of detecting one greyed-out Piece Definer paste button from another Piece Definer instance, I've just removed the greying out.
=> 10563 - Paste button in PieceDefiner no longer gets stuck greyed out

vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java, vassal-app/src/main/java/VASSAL/counters/Embellishment.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc
The CounterDetailViewer has an irritating quirk where one can't combine the "top layer only" filter with the use of a property match expression. All the other layer options can be duplicated from inside of a property match expression, but not that one.
So this allows the option to "do both".
Example: doesn't pick up the ginormous card underneath the mat (or for that matter the mat itself), but *does* allow multiple pieces to be picked up if they're all e.g.  overlapping markers. *Would* pick up the card if I rolled over that. 
I tried to "solve it from within the existing Vassal stuff" e.g. by making two different CounterDetailViewers and having one for e.g. Cards and one for e.g. Regular Pieces, but the problem is if I have a property match expression to get e.g. "only the cards" or …
=> 10552 - CounterDetailViewer - can combine layer filters with property match expression

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/java/VASSAL/configure/EditPropertiesAction.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Editor.adoc
So now when opening e.g. two Pieces (or a piece and a prototype) to copy things between them, it is no longer necessary to be constantly dragging the two configurer windows off of being right over top of one another.
```
//
// C+A             C+S
//
// A        C        S
//
// C+A+S           A+S
//
```
=> 10565 - While double-clicking to open component in Editor, holding Alt, Shift, and/or Ctrl affects the location the new window opens.

vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Apparently running the startup wizard completely bypassed all the Saved Game validation, like checking if you're trying to load the saved game into an earlier version of the module and printing a warning instead of throwing an exception.
=> 10643 - Players loading games through the starting Wizard should actually see saved game mismatch warnings (e.g. loading wrong version)

vassal-app/src/main/java/VASSAL/counters/Obscurable.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mask.adoc
Per @riverwanderer 's good idea in https://forum.vassalengine.org/t/mouse-over-to-show-unmasked-piece/72832/3
Masked pieces can be set to automatically display their unmasked versions in rollovers to players eligible to see the piece (i.e. owning players)
=> 10628 - Autopeek Rollover

vassal-app/src/main/java/VASSAL/build/module/PrototypeDefinition.java, vassal-app/src/main/java/VASSAL/build/module/PrototypesContainer.java, vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java, vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
Something I've wanted to fix for a long time, and certainly gets mentioned a lot by other module designers: until now when you changed a prototype you basically had to completely restart vassal (not even just restart the game -- restart _VASSAL_) because none of your prototype changes would be honored until you did -- they all get cached in various places. 
So this PR clears out the cache from startup stacks and piece palettes and the like whenever a prototype is changed. This not only fixes the problem Claudio originally described (cascading changes among multiple prototypes), it also fixes the palettes and startup stacks.
Doesn't affect performance for normal _Player_ operations because no prototype ever changes during a Player session.
In testing this out I opened a module and changed …
=> 9226 - When Editor changes a prototype, clear the prototype cache and all pieceslot caches

vassal-app/src/main/java/VASSAL/i18n/TranslateWindow.java
Fixes #10306 
The null check was at the wrong place.
=> 10306 - Fix NPE if try to open translations but the buildable doesn't exist

vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
Fixes #10028 and some duplicates. 
It was already trying to sanitize illegal characters from temp filenames, it just wasn't doing it soon enough and was getting caught on a library method getting mad and throwing an exception.
=> 10028 - Sanitize temporary file names a bit earlier

vassal-app/src/main/java/VASSAL/build/module/SpecialDie.java
Will have no effect on modules when a translation is not in effect, or if the Die Face names have not been translated.
=> 9295 Report translated name for Symbolic Die Faces

vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java, vassal-app/src/main/java/VASSAL/counters/SendToLocation.java, vassal-app/src/main/java/VASSAL/counters/Translate.java
Fixes #9800 
SOME situations were repainting the maps (e.g. if a piece was actually added to the map as opposed to a stack), but other situations were not (like merging a piece into an existing stack). 
I'm absolutely flabbergasted that this has existed for apparently forever.
=> 9800 - Fixed bug where Place Marker, Send-to-Location, and Translate traits didn't always repaint maps

vassal-app/src/main/java/VASSAL/command/MovePiece.java
Fixes #9759 
On this one we should be a bit careful about whether we're solving a problem that needs to be solved. 
The problem is that the MovePiece command used to process undo (unlike PieceMover when processing drag-and-drops) does not place *lone* stackable pieces into a new stack when it doesn't find any existing piece/stack to merge with. 
The PR handles making sure lone stackable pieces are placed into stacks. So it's _probably_ benignly harmless. But you know, stacks and movement and undo -- OH MY! 
I'm not _sure_ what the story is with that getParent()-and-insert-at-0 thing going on in there -- it seems like something that would never actually run or matter in this case.
=> 9759 - UNDO of movement will no longer deny lone stackable pieces their own stack (fixes some obscure stack-related bugs)

vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/PolygonEditor.java
A one-line fix that took 12 years to get done!
=> 5090 - Zone defining - when dragging a square to define initial zone, dragging at edge of screen scrolls

vassal-app/src/main/java/VASSAL/build/module/Inventory.java
Fixes #10698
@riverwanderer This should fix the GPIW bug you just encountered. The property you asked to group by was stored internally as not-a-string (but how would you know that) and Java got mad. Should no longer be a problem once this is merged.
=> 10698 - When inventory grouping specifies properties that aren't internally strings ... don't break

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
On maps with multiple board choices, SetupStack was sometimes using a different board to validate whether there was a grid or not than the board it was actually reading the grid from. (So sometimes went boom)
This removes the opportunity for inconsistency.
=> 9571 - Correct inconsistency in use of GetConfigureBoard

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java, vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java, vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Fixes #9890
* SGKCs are now guaranteed to fire in the order they are listed in the module. There's no need to support returning to the old functionality because the old functionality was (a) officially undetermined, so the fact that we're doing them in the right order fulfills their non-expectations (b) but in fact seemed to fire more or less in order anyway. 
* SGKCs can now be configured as to whether they fire (a) once per player session (the default and the old functionality), (b) every time a game is started or loaded during the session, or (c) once per *game* when the game is being started for the first time, either blank or from a predefined setup (i.e. the flag whether the SGKC has been applied is saved with the game)
* SGKCs cannot be undone past
=> 9890 - Startup Global Key Commands - always fire in order, can't be undone, and can be configured to e.g. "once per game"

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
* You have to turn it on with a checkbox (because it's a bit slow/sluggish) 
* -Possibly- it could be optimized and thus run faster? Also possibly that's not worth the trouble. 
* -Certainly- @BrentEaston could make the configurer layout look better
Even in sluggish mode it is something I will often want to use
=> 6476 Repositioning Stacks/Decks optionally draws ghosted images of other stacks/decks

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java, vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/build/module/map/BoardPicker.java, vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java, vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java, vassal-app/src/main/java/VASSAL/counters/Deck.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameRefresher.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/SavedGameUpdater.adoc
This supports basic deck refreshing:
(1) updates decks in the game to latest settings in module
(2) Optionally deletes decks from the game if the deck has been deleted from the module (any current contents of the deck will be left in a stack at the deck's former position)
(3) Optionally adds decks to the game if they have been added to the module. Does NOT add any contents to the deck, whether or not the module defines starting contents -- an empty deck will be added at the location. Module designer will have to work around adding contents by other means (e.g. dragging them in)
=> 9063 - Deck Refresher

vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
Place Marker was placing stacking pieces "Commando" if the placing piece was non-stacking.
Bug report was here:
https://forum.vassalengine.org/t/place-marker-doesnt-stack-counters/72928
=> 10750 - Place Marker should put stacking markers in a stack (even if parent marker is non-stacking)

vassal-app/src/main/java/VASSAL/counters/Deck.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Deck.adoc
=> 9118 - Fixed bug where Deck 'count expressions' wouldn't count beanshell, only old-style (now will count either)

vassal-app/src/main/java/VASSAL/counters/Footprint.java
To really no one's surprise given we're talking about Movement Trails, the earlier fix to MovementTrails (the one where the configurer was passing the value from the wrong field entirely into the setType) unmasked yet another bug, now with the localVisibility not being initialized properly at the start of a game. 
The correct initialization path for a field in a Trait that's neither properly Type nor State, but instead some this-machine-only flag is a bit opaque to me, but this looked worth a stab and Mark Benson said it seemed to fix his problem.
OH: also my sanity just couldn't take trying to parse those two-character configurer names any more.
=> 10760 - Further unbreak local-only trails

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Fixes #10792 
If the configurer had been the *primary* configurer of an earlier session, it might not have cached its bounding box.
=> 10792 - Fix NPE (Always cache bounding box)

vassal-app/src/main/java/VASSAL/counters/Footprint.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
MOVEMENT TRAILS SHAT THE BED. NEWS AT 11.
=> 10774 - Validation messages when Movement Trail traits placed inside of Rotate, Pivot, or Mat Cargo

vassal-app/src/main/java/VASSAL/counters/Deck.java, vassal-app/src/main/java/VASSAL/counters/Stack.java
Fixes #6195
Couple of things -- I ran through this bug in 3.6 and was not able to reproduce the effects. I even put a breakpoint on the deck out-of-cards thing to see if it was getting fired extra times. I'm not sure _when_ this problem stopped happening (I couldn't find a smoking gun in the git history), but anyway I could not reproduce it from the demo module.
However there is some stuff where deck properties could be getting updated extra times when merely rearranging the order of the deck, so I've provided a PR to address that.
=> 6195 - Don't thrash Deck properties when just rearranging order

vassal-app/src/main/java/VASSAL/i18n/I18nResourcePathFinder.java
The code that localizes images makes the assumption that the base language of the module is always English, so does not check if the is an English alternate for an image in the images_en folder.
=> 10772 Allow module images to have English localizations

vassal-app/src/main/java/VASSAL/build/module/properties/SumProperties.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc
Rollovers (and maybe other things) use the SumProperties class which allow $..$ substitution of a simple `$sum(propertyName)$` into the expression. But if Beanshell is used this local sum() quasi-property collides with the sum() we've built into Beanshell. 
So I've introduced an alternate syntax sumProperties() for folks to use inside their Beanshells.
=> 10762 - Fix sum() collision with beanshell for e.g. Rollovers, etc by introducing sumProperties() alternative

vassal-app/src/main/java/VASSAL/build/module/properties/IncrementProperty.java
=> 9124 - Property incrementers no longer apply turned-off min/max constraints

vassal-app/src/main/java/VASSAL/counters/ActionButton.java, vassal-app/src/main/java/VASSAL/counters/Decorator.java, vassal-app/src/main/java/VASSAL/counters/FreeRotator.java, vassal-app/src/main/java/VASSAL/counters/MatCargo.java, vassal-app/src/main/java/VASSAL/counters/Translate.java
Fixes #6075 
Also, getOuter() was failing if it happened upon a Set Global Property trait specifically. That's now fixed.
I have a rectangular button in Almoravid and I checked rotating it e.g. 45 degrees, and now you have to click exactly in the boundaries of the visible button (whereas before you had to click inside where you knew the pre-rotated shape would have been)
ALSO -- The get-cumulative-angle method in FreeRotator was ignoring MatCargo. Fortunately it was only called in Move-Fixed-Distance (Translate.java). So now... maybe it's fixed? (Merged this in from 10791 because there was shared code)
=> Action Buttons now respect rotation. Also fixed a bug in getOuter()

vassal-app/src/main/java/VASSAL/build/GameModule.java
I did a profile on this guys' huge 306mb World in Flames module where he said the Refresh Counters time had gone from "a mere 10 minutes" to more like 50 minutes. Anyway... the guys has some "interesting features" like 57 MAP WINDOWS. But anyway from watching the profiling I was able to isolate this one little place and make his module a fuckton faster. 
So it probably makes everybody's module a non-fuckton faster but still faster.
Anyway we should probably put it in 3.6-beta7 so he can try it out.
=> 10803 Speeds Game Refresh and general performance in modules with many maps defined

vassal-app/src/main/java/VASSAL/counters/ActionButton.java
If there was more than one action button on a single piece, it was only checking the first one for clicks.
=> Fix an action button oops

vassal-app/src/main/java/VASSAL/counters/Decorator.java, vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
(1) moved INNER and OUTER to the top of the properties check list for Decorator, since they're asked for the most
(2) Adjusted Decorator.getOutermost() to not call getProperty twice for the same thing
(3) Adjusted the ExpressionInterpreter to avoid throwing scads of NPE / NumberFormat exceptions when a piece doesn't have a particular property
None of these make the code _look_ any better but they run faster.
=> Misc property lookup optimizations

vassal-app/src/main/java/VASSAL/counters/RestrictCommands.java
They were evaluating the full beanshell even if the key being passed through wasn't the key they were restricting.
=> Optimization: Check for possible keystrokes in Restrict Commands before evaluating match epression

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/Console.java
Fixes a minor goof in 3.6-beta7 and one other minor console thing that has existed for a while.
(1) DrawingMouseoverIndex was returning an integer. This _ironically_ made it not work when offered to the Embellishment's Follows-Expression field -- it would have an expression evaluation error! So now it returns the "number" in a String, the way Vassal apparently wants it. This made it work as a valid property to pass to Follows Expression Value.
(2) The Console's "property show" was throwing if it was asked to show a non-string property value
=> DrawingMouseoverIndex correctly returned as string. Console now displays null valued properties instead of NPE

vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java, vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java
1. Fix access issue when refreshing Decks with new 'ownership' feature. Symptom is Deck disappears on refresh.
2. Fix issue where all cards from duplicately named Decks in module end up in the first defined Deck after refresh.
=> Fix Deck refreshing when running Game Refresher

vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/PolygonEditor.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java, vassal-app/src/main/java/VASSAL/counters/ActionButton.java
PolygonEditor.reset(Polygon, String) was totally broken. Use the proper API to set the polygon on the editor.
=> Directly setting coordinates in Zone definer fails to create a Zone

vassal-app/src/main/java/VASSAL/build/module/Inventory.java
This crept in when fixing the properties that weren't strings. But we don't want null ones to suddenly get reported.
=> 10876 - Remove unwanted nulls from Inventory

vassal-app/src/main/java/VASSAL/counters/Stack.java
See #10873 -- _something_ was adding a stack to a stack as a child. This would at least produce a stack trace in future cases (showing what code path was trying to do that), rather than the current behavior which is that the stack gets half-way inserted.
=> Added diagnostic to determine what is trying to add stacks to stacks

vassal-app/src/main/java/VASSAL/preferences/Prefs.java
Catch IllegalArgumentException thrown by Properties.load() when reading a corrupted prefs file and wrap in an IOException so we can show an error dialog. (Previously, a corrupted global prefs file could stop the Module Manager from opening and give the user no clue as to why.)
=> Show an error dialog if reading a corrupted prefs file

vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
I think buttons that initialized based on global properties that were truly global were working okay, but buttons initialized based on global properties that were part of Map windows (and so "didn't exist" until game setup fully activated) were not initializing properly.
https://forum.vassalengine.org/t/global-key-command-disable-bug/73222/5
=> 10907 - Disabled Toolbar Buttons on Map Windows didn't initialize starting state properly

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
... because setMap() was never actually called for those pieces. 
So let's call it now -- WHAT COULD GO WRONG?!?!?!?!
It is conceivable that this will fix other subtle bugs about some pieces not realizing what map they were on until they were moved for the first time. Or I suppose it could expose NEW AMAZING BUGS where we used to somehow depend on that behavior. 
https://forum.vassalengine.org/t/version-3-6-1-cant-get-and-action-button-trait/73208/7
=> 10903 - Incredibly, stacking units placed by At-Start stacks didn't allow Action Buttons on said pieces to function until the piece was moved

vassal-app/src/main/java/VASSAL/counters/KeyCommand.java
Fixes #10931
@BrentEaston this actually happened down from one of your DeckSendKeyCommand thing (Hooray! Someone is using one already!!!). Possibly this patch will just fix the whole problem, but since this is a newish structural addition, could you possibly check through your various DeckSOMETHINGKey things and make sure they're all copacetic with whatever nulls they're supposed to theoretically pass/not-pass?
=> 10931 - Fix NPE in menu text

vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
I don't think this happens with a *valid* property name, but obviously it shouldn't stack overflow on a bad one
Fixes #10951
=> 10951 - Fix stack overflow infinite loop if invalid property name put in blank

vassal-app/src/main/java/VASSAL/build/AbstractBuildable.java, vassal-app/src/main/resources/removed
Reinstate AbstractBuildable.getComponents(), since we're getting bug reports about it. (The dependency checker doesn't find that it's deprecated because it's attributed to the leaf class, not to AbstractBuildable...)
=> Reinstate AbstractBuildable.getComponents()

vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Set lastSaveFile to null if we're replaying a log, to prevent Save Game from clobbering the log.
=> Prevent Save Game from clobbering log being replayed 

vassal-app/src/main/java/VASSAL/build/module/Inventory.java
Comparing arrays using `equals() is never right if you aim to compare the contents. Also no point in creating arrays from Lists just to compare them.
=> Fix bad Inventory.Counter.equals()

vassal-app/src/main/java/VASSAL/build/module/GameState.java
* Actaully reset the save dialog filename before showing it, as it also  hangs on to the filename. AUGH!
* Don't suggest the name of the predefined setup as a save filename.
=> Reset save dialog filename after close of game

vassal-app/src/main/java/VASSAL/configure/StringEnumConfigurer.java
validValues might be an empty array; return an empty string in that case.
=> Fix ArrayIndexOutOfBoundsException in StringEnumConfigurer

vassal-app/src/main/java/VASSAL/launch/Editor.java
Disable URLConnection cache for jar URLs used by the Editor on Windows. This cache holds files open, preventing us from saving modules after something has been fetched using a jar URL.
=> Prevent URLConnection cache from holding edited modules open on Windows

vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Don't close map window when Map is removed from parent. This prevents the window from closing when the ConfigureTree is reordered in the Editor.
=> Editor: Don't close window when moving Map or other components relative to Map

vassal-app/src/main/java/VASSAL/build/module/ToolbarMenu.java
Fixes #11025 
I think that some other level of this object is *also* a PropertyChangeListener and was probably adding it in cases where the property change isn't produced by a JButton, so this one just needs to check and ignore those.
=> 11025 - Gaurd against ClassCastException when MultiActionButtons change property values

vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java, vassal-app/src/main/java/VASSAL/build/module/Inventory.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/NotesWindow.java, vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java, vassal-app/src/main/java/VASSAL/build/module/SpecialDiceButton.java, vassal-app/src/main/java/VASSAL/build/module/ToolbarMenu.java, vassal-app/src/main/java/VASSAL/build/module/map/ImageSaver.java, vassal-app/src/main/java/VASSAL/build/module/map/LOS_Thread.java, vassal-app/src/main/java/VASSAL/build/module/map/LayerControl.java, vassal-app/src/main/java/VASSAL/build/module/map/MapShader.java, vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java, vassal-app/src/main/java/VASSAL/build/module/map/PieceRecenterer.java, vassal-app/src/main/java/VASSAL/build/module/map/TextSaver.java, vassal-app/src/main/java/VASSAL/build/module/properties/ChangePropertyButton.java
AbstractToolbarItem Buttons weren't getting added as components.
Also a bunch of them do their own bespoke addTo without calling super, so had to retrofit it in there too.
=> 11060 - Fixes to various Toolbar Buttons that weren't respecting the "disable-on-global-property" settings

vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
These were somehow only documented in the Designer's Guide.
So now they are added to the online docs in various places.
=> Documentation updates for DrawingMouseover / DrawingMouseover Index

vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
Throw an IOException which we catch, instead of an uncaught IllegalArgumentException, when a temp file can't be created due to its name.
=> Improved error handling when a temp file can't be created

vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
The "map" field is not e.g. where the piece is, it's just where the SendToLocation trait thinks its target is. And since we have "send to target counter" with filters, it is possible for there to be no valid target, so map can be null. And in this particular case we were inside a "if (map != null)" so it looked like map couldn't be null, except the apply-on-move key can change that situation by changing what matches filters, etc. So I've moved the reference up above the place where it can change, since repaint is just a "schedule this" call anyway.
=> 11073 - Fix situation where Send-to-Location throws exceptions when it can't find target counters

vassal-app/src/main/java/VASSAL/counters/Deck.java
Fixes #11069 
The inner loadDeck() method can return null if the user picks a file that is not recognized as a deck.
=> 11069 - Fix crash in Load Deck when an invalid deck file selected in file picker

vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
Mark pointed out that the Send-to-Location's "send to nearest counter, filtered by properties" could make proper use of the same kind of $...$ source/target matching we do with global key commands. 
Here I have attempted to do that w/o having to restructure the entire Send-to-Location class -- I borrow the existing property filter, premasticate it for $...$, and then send the result onward to the actual matcher. 
This includes the fix in #11073
=> 11074 - Support Send-to-Location source/target matching with $...$ expressions

vassal-app/src/main/java/VASSAL/build/module/Inventory.java, vassal-app/src/main/java/VASSAL/build/module/map/TextSaver.java
Write text files in UTF-8, not the default encoding, so we can guarantee that all characters are encodable.
=> Write text files in UTF-8, not the default encoding

vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
Alternative fix for 11065: Don't filter out directory entries generally; selection of images for i18n depends on them. Instead skip the directory entries when creating a new ZipArchive.
=> Image directories for i18n were not found in 3.6.4

vassal-app/src/main/java/VASSAL/tools/DataArchive.java
Directory entries need not exist in ZIP archives if the directories have iles in them. Don't rely on their existence for finding directories of localized images.
=> Deduce the existence of localized image directories which lack ZIP entries

vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/HexGrid.java
The range in hexes between 2 points that are not in the centres of hexes can be out by 1 hex. In the worst case, 2 the hex range between two non-central points in the same hex can be 1 instead of 0. This affects the range displayed by the LOS thread and also the GKC range check.
=> 11099 Correct HexGrid range between points within a hex

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
GamePieceImage's configurer is too fucked up and byzantine and results in some NPE during the duplicate process. 
I've removed the duplicate option from Game Piece Image objects specifically (workaround is to use copy/paste)
=> Remove "duplicate this item" option from Game Piece Image 

vassal-app/src/main/java/VASSAL/build/GameModule.java
Fixes #11127 
It's insane that FilenameUtils 
(a) understands drive letter prefixes, where they are, etc
(b) but throws an exception if one's part of a string passed into the filename
(c) but DOESN'T provide a way to extract the non-prefix part of a path+filename in order to use the things w/o the stupid exception.
=> 11127 - Don't throw exception if there's a drive letter in a filename

vassal-app/src/main/java/VASSAL/launch/TilingHandler.java
Setting max heap to 3/4 RAM isn't effective on some systems and results in the JVM failing to start.
=> Use heuristic value for tiler max heap, retry with 50% more on failure

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java, vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
Somehow the pieces in his PieceSlot for his setupstack already thought they were *on a map*, but of course pieces in Piece Slots are supposed to be the "Platonic Forms Of Their Pieces". 
I can only suppose that some weird thing had happened in the past (direct xml file editing? something else?) that made just a few of his pieces have pieceslots that were somehow attached to a map. And so what he was seeing was the actual Platonic Form of his pieces!!! 
The reason it showed up _now_ was that I had it rebuilding SetupStacks "for safety" whenever game is set up (previously you could get zany results from multiple runs of game in one Player window, plus also more importantly this makes prototype editing more stable)
I've patched it by just making sure those things aren't allowed to be "on a …
=> 11160 - Prevent At-Start Stacks from creating additional spurious pieces on main map

vassal-app/src/main/java/VASSAL/build/module/GameState.java
I set out originally to fix the Discord drag-and-drop situation, and I was thinking that would require changing the place we do the save/not-save/cancel prompts. In the course of working on it I discovered the original (Discord link) problem could actually have been fixed without other changes, however given the various discussions we've had recently about the awkwardness of our existing "wait until we've loaded the whole file before asking if you wanted to save the game or cancel" method, and indeed the fact that the Cancel button didn't produce a coherent result in some of the cases, I decided to proceed with the full order change that I'd embarked upon.
=> 11135 - Prompt to save/discard/cancel before loading the new game. Fixed Discord drag-and-drop bug. 

vassal-app/src/main/java/VASSAL/build/module/Console.java
Would like this in 3.6.5 -- when people send me games and I want to look at the errorlog or whatever, not being able to type the console command for it always drives me crazy (for some reason our Show Errorlog is only in the module manager, which doesn't help me when I'm running some master or test version)
=> The errorlog console command is available it at all times

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
ZoneProperty _extends_ GlobalProperty so there actually needs to be a conversion of the object when copy/pasting in this situation.
=> Copy/Paste conversions fixed for Zone Properties to/from Global and Map Properties

vassal-app/src/main/java/VASSAL/build/module/Map.java
This just sorts out confusion between different drag-drop handlers -- prevents dragging a file/link onto the map window from triggering any spurious drag-at-edge-of-screen behaviors.
=> 11233 - UI Cleanup: don't scroll-at-edge the map if a file or link is being dragged instead of a piece

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/configure/IconConfigurer.java, vassal-app/src/main/java/VASSAL/configure/ImageSelector.java, vassal-app/src/main/java/VASSAL/configure/SoundConfigurer.java, vassal-app/src/main/java/VASSAL/counters/ImagePicker.java, vassal-app/src/main/java/VASSAL/tools/icon/IconFamily.java
So for example if you are going back and forth between playing a game (loading log files) while editing some other module, you won't keep being asked to pick a saved game from your art directory or vice versa.
=> 11260 - Editor now remembers its most recent image-picking (and sound) directories separately from its memory of last save/load of games and logs

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/documentation/AboutScreen.java
We added these extra "Other" fields a while back but didn't make a way for a downstream user to report them to us/me.
=> 11279 - Module "other" strings displayed in About screen

vassal-app/src/main/java/VASSAL/tools/image/ImageUtils.java, vassal-app/src/main/java/VASSAL/tools/imageop/ScaleOpBitmapImpl.java
This ensures that the sum of tile widths and heights equals the overall image width
and height.
=> Scale tiled images to target size rather than by scale factor

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Hooray for things being null and getting checked for that
(No issue number needed, I think I introduced this in code checked in after 3.6.5 -- HOORAY ME!!!)
=> Apparently stack name can be null sometimes during initial adding-to-module

vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Preferences.adoc
I've continued to gradually extend the ability for module designers to set the "default-for-their-module" for various preferences via Global Properties.
=> 11303 - Preference to control drag-at-edge scroll rate, plus Amazing New Default Powers

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/ZonedGrid.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
SetupStack has a "Use grid location" checkbox, but *unlike* the Send To Location trait it *cannot* send to the name of a grid location in an Irregular Grid (aka "RegionGrid") if the Zone for the grid is set up to use only the zone name (e.g. "$name$" instead of "$gridLocation$").
This is super irritating because it is often desirable to define explicit send-points inside of a larger region (which we can already do with Send To Location) even if the larger region (zone) just reports its zone name as the location name. 
This change allows SetupStack to participate in the goodness -- it will now perform a complete search the old way like before, but if it comes to the point where it finds nothing and was literally just going to throw an exception and print an error message, it will instead …
=> 11356 - SetupStack can match literal grid names even if Zone only reports Zone name (e.g. uses $name$ as Location Format)

vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/PolygonEditor.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
* If SHIFT held down, moves whole shape instead of just one vertex
* If no vertex selected, then arrow keys likewise move whole shape
* TAB between selected vertices
* ESC deselects
Added info on these features to the window legend
=> 11348 - Polygon Editor improvements (move whole shape, tab between points)

vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNotesController.java
* Turn on sortable columns in the private notes table.
* Provide a cell renderer for the private notes date column, to allow the display text to differ from the sort key.
=> Make columns in Delayed Notes table sortable

vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
They were showing up incorrectly in remove-unused-images
=> DoActionButton claims its icon in remove-unused-images

vassal-app/src/main/java/VASSAL/counters/BoundsTracker.java
BoundsTracker was always repainting the entire map. This change has BoundsTracker repaint just the regions of the map that the added Pieces report.
**User Impact**
I don't know the general user impact of this fix. BoundsTracker is not used that many places. 
**Why this PR?**
I am working on a "stack slots" feature and was using BoundsTracker to track changes to the stack. The feature repaints the screen frequently in the case where you're "scrubbing" a piece over an expanded stack and slots are appearing/disappearing rapidly. 
The code was performing in a slow and glitchy way.
When I made the adjustment in this PR, the code performed quickly again.
So, in the case where you're using BoundsTracker and calling repaint often, there would be a big benefit in this adjustment.
**Risks**
This …
=> BoundsTracker - Track bounds and repaint just for the regions of added pieces; rather than the whole map.

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
If a prototype definition includes a "BasicName" trait, then it will be auto-displayed as part of the "description" of the prototype when viewed in the editor. (That way if a BasicName trait is used, it becomes part of the normal description of the prototype/piece without the string needing to be manually copied somewhere else -- "duplication of code")
=> 11545 - Description of Prototype will auto-include any BasicName

vassal-app/src/main/java/VASSAL/counters/Labeler.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Label.adoc
Heretofore, a TextLabel where the label is currently empty/blank did not run its Name Format evaluation (just left the name of the piece alone). 
However I have discovered some situations where I want to change the name of a piece based on a property, and using a "dummy" text label that otherwise doesn't display (just runs its name format) is presently the only workaround available (besides typing the name of every piece a whole extra time in a whole different place, effectively "duplicating code"). So this checkbox allows me to use TextLabel as a workaround.
=> 11524 - Option to 'always use format' on text label (even if label is blank)

vassal-app/src/main/java/VASSAL/build/Widget.java, vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java, vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java, vassal-app/src/main/java/VASSAL/build/widget/TabWidget.java, vassal-app/src/main/java/VASSAL/i18n/Localization.java
Combined Translation fixes
- Translated Tabs in GamePiece palette no longer lose translation when a new tab is selected.
- Piece names in Scrollable Lists in Game Piece palette are now shown correctly translated.
- Sub-Widget names in Scrollable Lists in Game Piece palette are now shown correctly translated.
- Game Piece palette window name can now be translated.
=> 11540 - Display translated Basic Piece/Basic Name in Scrollable lists in Game Piece Palette

vassal-app/src/main/java/VASSAL/counters/AreaOfEffect.java
There is a bug related to boundstracking reported by @Amàndil Eremanth.
The code fix in this PR makes sense to me and should fix the issue. 
**Bug repro steps**
Use 3.6.8 build (from master ok).
1. Load up his module
2. New Game
3. Select "Jugador 1"
4. Select "Adoquinado 1"
5. Click "EJERCITOS" button.
6. Select "Sauron" and drag piece to map
7. Click on piece to select.
8. Move mouse off to the side (away from where the AOE will appear).
9. Click `M` on the keyboard to display the AOE.
You'll see that AEO is only partially displayed (only within the bounding box of the piece).
=> Add AOE bounds to `boundingBox()` method.

vassal-app/src/main/java/VASSAL/counters/BoundsTracker.java
BoundsTracker was recently updated to trigger a redraw just part of the map (rather than the entire map).
This revealed some bugs and oddities. One of these bugs/oddities was the fact that when a piece reports its bounds via `boundingBox()` it does not include its offset position in the stack. In some cases we want the offset position and in some cases not. There were a few options considered:
(1) repaint both the boundingBox of the GamePiece AND the boundingBox+stackOffset of the GamePiece.
(2) have each GamePiece report whether its draw area is offset with the stack or not, perhaps defaulting to true.   Then you could have a boundingBoxWithStackOffset() method or even boundingBox(withStackOffset: true) which would include the stack-offset when needed.
(3) track/repaint the parent stack, …
=> Fix bug in BoundsTracker: Not correctly tracking the redraw bounds of pieces that are within a stack

vassal-app/src/main/java/VASSAL/configure/BeanShellExpressionConfigurer.java
(Followon of feedback from Mark that the Ctrl+Z "undo" wasn't enabled in Expression Builder -- doesn't need a Changelist entry)
=> Expression Builder - enable undo of text

vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java
This adjustment to the disabled TurnCounter "-" behavior allows the designer to maintain control if desired. Previously, the "-" button functionality was observed to be able to be overridden by HotKeys and could lead to accidental player control and was therefore bypassed. However, there are valid use cases where the designer would need to exercise the "-" function while denying it to the player. The bypass is therefore removed in this adjustment, returning control to the designer.
=> tweak to allow designer control of TC backwards function when disabled

vassal-app/src/main/java/VASSAL/build/module/Map.java
Bug: https://github.com/vassalengine/vassal/issues/11597
Problem with map that don't have a launch button (but do have a hotkey). When you try to close them, VASSAL tries to close the game rather than simply hiding the window.
=> Get the CloseWindow event to look at other ways of reopening the window apart from the button

vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java, vassal-app/src/main/java/VASSAL/counters/KeyCommand.java
Making this available so @uckelman can easily see the results in different modules.
Discussion here:
https://forum.vassalengine.org/t/right-justify-context-menu-commands-v3-6-8/75000/18
**IMPORTANT -- Code does not change the tooltip for menu buttons**
This code does **not** effect the display of keyboard shortcuts for the menu buttons. It does not look possible / easy to update the menu-bottons to show symbols. I think this code is an improvement on what was there previously, but perhaps introducing this mismatch between the menu-buttons and the context menus is worse.
=> Player context menus: Show keyboard shortcuts right-aligned and with symbols.

vassal-app/pom.xml
A newer version of logback is required to work with SLF4J 2.0.
=> Upgrade logback

dist/VASSAL.sh
On Linux, I have noticed that VASSAL will not start if the executable script (VASSAL.sh) is run through a symbolic link. 
To reproduce the issue, unpack VASSAL into any location (I used /opt in my case), then create a symbolic link to `/opt/<VASSAL FOLDER/VASSAL.sh`, e.g. with the latest version:
```sh
ln -s /opt/VASSAL-3.6.7/VASSAL.sh vassal
```
Then call the symbolic link:
```sh
./vassal
```
You will get the following error:
```
Error: java is too old to run this version of Vassal. Please use Java 11 or later.
```
I noticed it because I was running java 11.0.8 so the error message could not be possibly correct.
The reason for this behavior is that the executable script (VASSAL.sh) will attempt to identify the installation directory a combination of `which` and `dirname`, but this will …
=> Dereference symbolic link to executable before attemping to find install dir

vassal-app/src/main/java/VASSAL/launch/Launcher.java
Exceptions thrown when launching are bugs. Don't swallow the exceptions.
=> Report exceptions thrown while loading modules

vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
getLocalizedConfigureName() is trying to expand the piece, even if one does not exist yet.
=> 11813 - NPE in PieceSlot.getLocalizedConfigureName()

vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
Change equals() to Objects.equals()
=> 11823 - NPE in GameRefresher when refreshing unnamed Decks

vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
It appears that the Fast Match setting for Mats/Mat-Cargo was subject to malfunctions based on sometimes passing "only part of the piece" (i.e. not passing the outermost trait) to matches
=> Global Key Command fastmatch for Mats fixed to avoid certain trait-order bugs

vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java, vassal-app/src/main/java/VASSAL/tools/io/DirectoryTreeDeleter.java
FileUtils to do it. Because it does no checking for exclusions (among other thigns), it's twice as fast.
=> Clear Tile Cache with more efficient Files.walkFileTree()

vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java, vassal-app/src/main/java/VASSAL/tools/DebugControls.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Noticed the need for this while I was working on Imperial Struggle module. Doesn't display the extra stuff on e.g. maps-that-only-have-one-board, so most people won't see anything extra/spurious/new
=> 11911 - Debug window shows board-relative coordinates if they are different from the map-relative ones

vassal-app/src/main/java/VASSAL/build/module/metadata/AbstractMetaData.java, vassal-app/src/main/java/VASSAL/build/module/metadata/ModuleMetaData.java
Turns out I had already solved this, except for 2 bugs which meant that it had never work!
=> 11929 - Show translated module name and descriptions in Module Manager

vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
Fortunately (having just looked through the various Mac keyboard types), there don't seem to maaaany European keyboards that go this weird way on the number key row.
Apparently the "new" treatment began in Vassal 3.6.7
=> Since 3.6.7, French/Belgian AZERTY keyboards on Mac were experiencing problems with Ctrl / Alt keys on the number key row

vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java, vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
In every other type of report (e.g. Report traits, DoActionButtons, etc) the report is formatted beginning "* " (a space after the asterisk). But for GKCs it is oddly not, leading to SLOPPY OUTPUT. 
This fixes them to be consistent with the other reports.
=> 11957 - Spaces in GKC reports made consistent with all other reports

vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/Symbol.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Extremely minor change, would be good for 3.6.12
=> 11986 - Add missing Section size symbol to NATO markers

vassal-app/src/main/java/VASSAL/counters/Decorator.java
=> 11884 - 'OldMat' properties now set correctly regardless of order of Mat Cargo and Send-to-Location (etc.) traits

vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java, vassal-app/src/main/java/VASSAL/build/module/map/MovementReporter.java, vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
There was zombie code from back when (in the terrible Bad Old Days) whether to mark pieces moved was sometimes treated as a user preference (ouch! head! exploded!) 
Anyway, modules which still had "Use User Preference" set in them were sometimes still (ack) heeding the terrible advice of the user. 
Zombie, meet FLAMETHROWER!
=> 11961 - Clear up mark-when-moved problems for modules which still had a legacy value set

vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java
Fixes #11437 
Apparently menu_item can be null, and the other parts of this method were protecting against that -- so this slightly newer part of the method should protect as well.
Oh right of COURSE it can be null because when there are no key commands rather than send an "empty list" we instead apparently send an array of length one that contains a KeyCommand.NONE
=> 11437 - Right-clicking on a Deck with no menu items no longer produces an exception

vassal-app/src/main/java/VASSAL/build/module/Inventory.java
=> 11462 - Don't +1 inventory sum if property isn't even defined

vassal-app/src/main/java/VASSAL/launch/AbstractLaunchAction.java, vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java, vassal-app/src/main/java/VASSAL/launch/UseTracker.java
Reinstate removal of module tile cache when a module is removed from the Module Manager, but only if no modules are open, to guard against deletion of an in-use cache.
=> Reinstate removal of module tile cache when a module is removed from the Module Manager

vassal-app/src/main/java/VASSAL/build/GpIdChecker.java, vassal-app/src/main/java/VASSAL/counters/Labeler.java
=> 9786 - Text Label traits will respond to GameRefresher (unless trait has a manually-change-label hotkey defined)

vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java, vassal-app/src/main/java/VASSAL/build/module/properties/EnumeratedPropertyPrompt.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/DynamicProperty.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalOptions.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/SetGlobalProperty.adoc
Purge blank property prompts.
But could someone actually be *relying* on the ability to set a property to blank from one of these menus?
=> 11178 - Omit empty lines in non-blank property setting prompts

vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java, vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameModule.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Is this a good idea or a terrible idea? I *think* it will run once at game start (from perspective of whoever started the game) and then once whenever someone joins/changes-side (from their new side's perspective). 
I was thinking it could be used to solve the classic Vassal problem where when you start a game you have to go immediately "flip all your cards upside down" (or pieces or whatever) because them just starting upside down can't be part of the initial state because of our encoded-by-passwords method of turning things face down.
=> 11918 - Startup GKC that fires when player joins or changes sides

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Fixes #11100 and #11101
Previously "Begin Logfile" had the undocumented (and unchangeable) hotkey Alt+W, and "End Logfile" had no hotkey
Now Begin Logfile's hotkey can be changed, End Logfile gets the default hotkey Alt + Shift + W and can be changed.
=> 11100 - Allow begin-logfile and end-logfile to have configurable hotkeys in Global Options

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/java/VASSAL/configure/ExtensionTree.java
When the user deletes something in the editor (from somewhere in the tree), it handles "properly removing that thing from its parent". But any of its children/grandchildren, whether they're in folders or just other kinds of children/grandchildren/etc? Nope, never "removeFrom's" them, etc. Meaning in this case that they never generate calls to "removeGameComponent" and so until module is reloaded there are still sometimes little treacherous references to them laying around. 
I guess when actually deleting something we need to traverse the tree and manually throw each individual child out the airlock.
=> 12048 - Fix bugs when deleting groups of decks/stacks from the editor

vassal-app/src/main/java/VASSAL/build/module/PrototypesContainer.java, vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
This one could be 3.6.14 if desired
Two prototypes w/ the same name will still only have one of them "found", but this solves the problem where when duplicating a prototype (either by copy/paste or the duplicate option) you ended up temporarily with two of the same name, and even when you renamed the new one to some new name it made the prototype container "forget about" the original prototype until you reloaded the module.
=> Duplicating a prototype no longer disables that prototype until next module reload

vassal-app/src/main/java/VASSAL/counters/UsePrototype.java
Fixes #11249
Apparently needed to put a bit more of that code inside the recursion limiter
=> 11249 - Enhanced recursion protection to catch self-referencing prototypes

vassal-app/src/main/java/VASSAL/configure/ColorConfigurer.java
#Fixes 12041
When color configurer was translating "no color" as null. Which worked okay in traits, but in attributes it meant our XML code didn't actually write/copy a record for that attribute. 
Worked around by returning the string "null" instead, which the configurer's StringToColor already turns back into a real `null`
=> 12041 - Rollover border color of 'no color' did not save to file, nor copy correctly

vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
Fixes #12061 
Fixes #12062
It appears that by pasting a sufficiently incorrect/incomplete regex expression, you can make Beanshell's eval thing return a null. So in the tradition of beanshell expressions I've made that quietly fail returning a "" the way it does with other exceptions.
=> 12061 - Fixed bug with pasting invalid/incomplete regex expressions

vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java, vassal-app/src/main/java/VASSAL/tools/NamedKeyStroke.java
Current implementation may not allow Mac to *bind* DEL/Backspace as a hotkey, but it will still successfully match DEL/Backspace for any module where it HAS been bound. 
To work fully right, Mac version will need either:
(a) exactly this
(b) Or possibly be told to ignore Backspace/Delete on the keyPressed side of things
(c) Or possibly be told to ignore Backspace/Delete on the keyReleased side of things
(d) Or possibly (but unlikely) something even more crazy/stupid
=> 11919 - Allow DEL/BACKSPACE to be mapped as a hotkey

vassal-app/src/main/java/VASSAL/build/AbstractBuildable.java, vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java, vassal-app/src/main/java/VASSAL/build/module/folder/PrototypeFolder.java, vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Appears on Editor menu when right-clicking any editor item
Exports selected object "and all of its children" to an XML file
XML file can then be imported to become the child of whatever is selected at the time of import.
GO FORTH AND SIN NO MORE!!!
=> 12067 - The BLACK BOOK OF EXPORT -- Editor allows import/export of groups of items as XML files (eg to transfer between modules)

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
* It was printing an extra separator when nothing was displayed on the other side
* It wasn't allowing imports to the root element, which should be allowed (only exports of the root node are disallowed)
(Thx @riverwanderer for testing and calling this to my attention)
=> Minor fixups in ConfigureTree menu -- no Changelist Entry needed

vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
@riverwanderer I think what was going on in 12077 might have involved ObscuredToOthers, which I think is the only thing you were using "unary !" with. This actually also does MOST of the thing you'd requested in some other item -- gives pieces a "false" to return if they don't have a Mask property.
=> 12077 - ObscuredToOthers can be counted on to be 'false' for pieces that don't even have a Mask property

vassal-app/src/main/java/VASSAL/build/module/Documentation.java, vassal-app/src/main/java/VASSAL/build/module/documentation/HelpFile.java, vassal-app/src/main/java/VASSAL/launch/PlayerWindow.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Basically if a module designer goes to the trouble of making some specific help for the module, then that is the stuff that ought to be at the top of the help menu.
I based this on 3.6.15 since it could go there. But it could also be punted into 3.7 if we're not looking for more, or not looking for trouble, or whatever.
=> 12084 - Help menu shows module-specific help items before generic Vassal ones

vassal-app/src/main/java/VASSAL/build/module/GameState.java
Apparently I accidentally disabled the display of load comments sometime during 3.6 while "cleaning up code" hahaha
=> 12119 - Restore vanished Load Comments

vassal-app/src/main/java/VASSAL/counters/Labeler.java, vassal-app/src/main/java/VASSAL/tools/swing/DataArchiveHTMLEditorKit.java, vassal-app/src/main/java/VASSAL/tools/swing/DataArchiveTextPane.java, vassal-app/src/main/java/VASSAL/tools/swing/LabelerDataArchiveHTMLEditorKit.java
If a Text Label trait is wrapped in <html> tags and ALSO contains an <img> tag, then we use JTextPane instead of JLabel to draw its HTML, which allows us to use the DataArchiveHTMLEditorKit previously developed for e.g. the Chat Log
=> 12100 - Text Labels support <img> tags

vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java, vassal-app/src/main/java/VASSAL/tools/LaunchButton.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
=> 12127 - Toolbar buttons disableable by a property (e.g. GKC, ActionButton, etc) can be set to hide when disabled

vassal-app/src/main/java/VASSAL/counters/BorderOutline.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/BorderOutline.adoc
This is an improvement to a feature that didn't exist until 3.7.0-beta1.
=> BorderOutline trait accepts two fields

dist/VASSAL.sh
Correctly handle paths containing spaces.
=> Correctly handle install paths containing spaces in VASSAL.sh

vassal-app/src/main/java/VASSAL/build/module/properties/ChangePropertyButton.java
Fixes #12155 
In this case it makes no sense to spurt out a blank line anyway. If somebody (inconceivably) depends on it, they can output a space and it will show the empty line.
=> 12155 - Change-property buttons don't generate completely empty chat lines.

vassal-app/src/main/java/VASSAL/tools/FormattedString.java
When reporting an error in the evaluation of a formatted integer field, the Audit report was reporting the outermost trait instead of the trait that was the source of the error.
=> 12209 - Report correct trait in expression Audit Trail

vassal-app/src/main/java/VASSAL/counters/Embellishment.java
(this is a minor fix an earlier 3.7 feature so may not need a change list entry)
=> Patch only-display-when configurer to use correct initial value

vassal-app/src/main/java/VASSAL/counters/BorderOutline.java
(Minor fix/improvement to new 3.7 feature -- it wasn't adding the property names to the searchable list)
=> Add BorderOutline's property names to the searchable target list

vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
Brent noticed this edge case last night ... right after we released 3.6.16 hohoho
Basically things like ... when you refresh a piece it might turn out the new version _doesn't have a Mat trait any more_ and stuff like that.
=> 12237 - Fix edge case Mat Refresh bugs

vassal-app/src/main/java/VASSAL/counters/Decorator.java, vassal-app/src/main/java/VASSAL/counters/MovementMarkable.java
(CHANGES note -- this is a between-betas patch to 3.7.0, so new in the next beta or release but nothing "new" from 3.6 to 3.7, if that makes a difference in changelist)
=> 12215 - New MarkMoved commands shouldn't default to being displayed if no key commands entered

vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
Fixes #12208
Toolbar buttons are just a total mess (the weird frankenstein thing they do with "menus") -- pulling this out for the moment & probably forever-until-V4
(CHANGELIST - This is just an internal 3.7 patch, removing a feature also added for 3.7, so changes between betas but not from 3.6)
=> 12208 - Remove hide-when-disabled feature for toolbar buttons that was breaking other things

vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
piecePosition is in component coordinates, not drawing coordinates, so its scale factor should not have the UI scale factor applied to it.
=> Fix incorrect drag offset on Windows with UI scaling > 100%

vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/HexGrid.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/MapGrid.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/SquareGrid.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/ZonedGrid.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
I am not familiar with the Vassal codebase, so this might not be a good approach to fixing the issue, or it may have bugs in it. I have only tested the specific case with `HexGrid`, not the other types of grids, or other situations than the one described in #12070 .
In particular:
- Are the changes in `RegionGrid` correct?
- Are the changes in `SquareGrid` correct?
=> Fix Inaccurate Hex Grid location reports

Makefile, vassal-doc/src/main/designerguide/designerguide.adoc, vassal-doc/src/main/userguide/userguide.adoc
Set the optimize attribute from outside the asciidoc files. This works around a problem that anyone trying to build on Windows will have with asciidoctor being unable to find Ghostscript.
https://forum.vassalengine.org/t/rghost-issue/11724/12
=> Avoid requiring Ghostscript when building without the Makefile

vassal-app/src/main/java/bsh/BSHUnaryExpression.java
Modified Beanshell parser to treat anything that is not true/false or "true"/"false" as false, instead of throwing a Data Module Error.
=> 12327 ! operator will always return false, not error if arg is invalid

vassal-app/src/main/java/VASSAL/build/module/Map.java
Summing scaled board locations accumulates rounding error; scaling summed board loactions does not. Do the latter.
=> Scale summed board locations instead of summing scaled board locations to reduce rounding error

vassal-app/src/main/java/VASSAL/preferences/BasicPreference.java
Currently, Global Option Preferences are ignored and their Global Property is never created if no Tab name is supplied. New behaviour is to create and initialise the Global property, but not include the Configurer on any tab.
=> 12363 - Initialise Global Option preferences that have no Tab name

vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
Issue introduced into 3.7 beta. Waiting for Mark to check it works OK on MacOS.
=> 12401 - Allow Ctrl-V to be entered as a Key Command

vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
Not sure if you want to handle this a a PR, or just revert #12078, but it was in an earlier beta, so might be better to handle it this one.
Original fix has a reasonably high probability of cause module behaviour changes. The fix is fixing something that doesn't really need fixing, so I have added additional documentation to explain the situation (in another PR).
=> Revert #12078 - Do not return a default value for ObscuredToOthers

vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
Prior to allowing Does Not Stack pieces to Stack, movement limitations in the Stack Viewer where dependent on the piece already being Non-stacking. When Stacking was added to Does Not Stack, the Stack View configurer was not updated to reflect the fact that the non-movement options should now be selectable independently from the non-stacking option.
=> 12495 - Mouse-over Stack Viewer 'Show move limited pieces' option no longer dependent on 'Show non-stacking' option.

vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java, vassal-app/src/main/java/VASSAL/tools/imageop/FixedScaleOpBitmapImpl.java
Extend Boards by a pixel to account for location rounding.
=> Extend by one pixel Boards with locations that round up, to prevent gaps

vassal-app/src/main/java/VASSAL/build/module/properties/ScenarioPropertiesOptionTab.java
Tweak to new beta option to allow Obververs to lock/unlock Scenario Options if no sides have been taken (assuming password matches). Allows Module Designer to manipulate these without having to take a side.
=> Scenario Options - Allow Observers to Lock option tabs if no Sides taken

vassal-app/src/main/java/VASSAL/counters/BasicPiece.java, vassal-app/src/main/java/VASSAL/counters/Clone.java, vassal-app/src/main/java/VASSAL/counters/Decorator.java, vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java, vassal-app/src/main/java/VASSAL/counters/Replace.java, vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Clone.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Concepts.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePiece.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Marker.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
Add ParentId property to placed markers.
Update all related documentation
My apologies for this extra one, but it is big issue for more advanced module designers and makes using place markers far, far easier without needing reams of traits to process communication back to the parent piece.
=> 12444 - Implement real Unique Piece Id property UniqueID that does not change during refresh. 

vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Change Window title of trait editor window from getDescription() to getBaseDescription(). Full description is not needed when editing traits and looks untidy. Plus it seems window titles do not natively support HTML, so the Comment trait was display raw html in the title.
=> 12549 Simplify Trait edit window title

vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/map/MapShader.java
The UniqueIdManager in MapShader is not need and not used. Replaced with a UniquelyNamedChildren validator on the Map instead.
=> 12556 Map Shaders on different maps can now have same name

vassal-app/src/main/java/VASSAL/build/module/Map.java
preferredCenter should be in map coordinates, not component coordinates
=> Center of map view during zoom used incorrect coordinate space

vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNotesController.java
Convert selected delayed notes table row to model, and get note object that way. JTable.getValueAt() indexes the columns as displayed, which is not the same order as in the table model if the colums have been reordered by the user.
=> 12324 - Fixed ClassCastException caused by reordering columns in Delayed Notes table

vassal-app/src/main/java/VASSAL/configure/ChooseComponentDialog.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Check that editorWindow is nonnull before trying to use it.
=> 12411 - Fixed NPE when updating ConfigureTree

vassal-app/src/main/java/VASSAL/build/GpIdChecker.java, vassal-app/src/main/java/VASSAL/counters/Labeler.java, vassal-app/src/main/java/VASSAL/counters/Replace.java
If `match current state` is specified, then non-changeable Text Labels should be excluded from the state match process.
=> 12688-Replace with other should not update text of unchangeable labels

vassal-app/src/main/java/VASSAL/build/module/ChessClockControl.java, vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
If the number of sides defined in the current translation does not math the number of sides defined in the module then
1. Report a Validation error when saving module from Editor (and in errorlog when loading module)
2. Do not translate sides in Player mode
3. Add warning message to chat window in Player mode.
Also includes earlier tweaks to side translation.
=> 12708 - Prevent ArrayIndexOutOfBoundsException if side translation count does not match module

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Search.adoc
Trying to add a checkbox option for Regular Expression search.
=> Support regular expressions in Editor search

vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameRefresher.adoc
=> 12260-Pre & Post Refresh Hotkeys

vassal-app/src/main/java/VASSAL/configure/AudioClipConfigurer.java
Support for expressions in the Sound Clip Configurer was added in 3.7.0, but it does not work correctly.
=> 12769 - Fix support for expressions in Sound Clip Configurer

dist/VASSAL.sh
I moved `set` a little lower in the script so it doesn't exit when checking if Java is installed.
See issue: https://github.com/vassalengine/vassal/issues/12810
=> Execute set later

vassal-app/src/main/java/VASSAL/tools/ScrollPane.java
Vassal already supports vertical scrolling of the map via the mouse wheel. This MR adds horizontal scrolling via the mouse wheel as well.
Amongst real mouse wheels, this also enables omnidirectional scrolling via
- two-finger trackpads usage on laptops, and
- middle mouse + [trackpoint](https://de.wikipedia.org/wiki/Trackpoint) movements
Here is a video of the change in action. I think it feels really nice.
[Screencast 2023-10-13 00 15 31.webm](https://github.com/vassalengine/vassal/assets/263263/1f40580a-c17e-44a3-b14e-db1ab5f4c80f)
- in general, zooming and scrolling the map feels quite juddery. I wonder if there is anything we can do about that
- Don't ask me why swing exposes horizontal mouse wheel movements as mouse release events :shrug: 
- The change is inspired from a very similar …
=> 12808 - Horizontal scrolling now supports 2-finger-trackpad and mice with additional horizontal wheels

vassal-doc/src/main/readme-referencemanual/ReferenceManual/Editor.adoc
also a clarification / correction.
=> Documentation: Editor Search section - add a cross-link to main search details.

vassal-app/src/main/java/VASSAL/build/module/map/deck/DeckSendKeyCommand.java, vassal-app/src/main/java/VASSAL/build/module/map/deck/DeckSortKeyCommand.java
This fixes deck sorting not working on the next and each subsequent "File->New Game". The deck sort HotKey works the first instance of a game module. After a "File->Close" and then "New Game", the sort HotKey does not work. The workaround prior to this fix: user must completely exit Vassal and restart it.
The sortListener must be null to successfully assign a new HotKey during initialization.
=> Deck Key Commands do not work on subsequent new games

vassal-app/src/main/java/VASSAL/counters/Labeler.java
Currently a label font using italics can run off the edge of its bounding box, as you can see with the "0" here:
This is actually a quirk of italics, as the `getFontMetrics` function does logical vs visual calculations. Old but relevant conversation at https://bugs.openjdk.org/browse/JDK-4262130, from which I borrowed for the solution.
Original conversation starts at https://discord.com/channels/740127632586178572/911199889059360798/1178520800928735272 for those interested.
=> Labels have incorrect bounds when using italics

vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
If you run the wizard and use the arrow to move up and down the pre-defined setup combobox, then each PDS you hit as you arrow is concurrently loaded in a new thread. This creates mayhem on a module with longer save load times. I was able to easily generate an out of memory error and fingers-crossed, this may be the root cause of the Sudden Wizard Death Syndrome.
I have removed the background loading and now load pre-defined setups in the foreground. Wizard users on large modules who use the arrow navigation method on drop-down boxes will notice a performance lag until each PDS loads. Normal people will see no change at all. External games are still loaded via a thread, but this is not as a problem as there can only ever be one.
=> 12912 Prevent Welcome Wizard loading multiple pre-defined setups concurrently

vassal-app/src/main/java/VASSAL/configure/PropertyExpression.java
This PR suppresses the most common bad data errors that are generated by pieces on a palette. The issue arises when a boolean expression such as {x && y} contains properties that are neither true or false. This can happen for spurious reasons in that some properties aren't correctly initialised until instantiated onto a map ... e.g. `<layer>_Active`.
The PR checks whether the source of the error ("owner") is an Editable Piece and if so, the bad data report is not issued unless that piece is on a map (map name != null).
=> Suppress piece palette boolean bad data errors

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Fix vulnerability to exceptions in PR #12798
Make Resource.getString explicit.
Handle [Module] and [Help Menu] correctly, so that contents of these components will be reported.
Clean out some build warnings.
Safeguard Prev from (unsupported) use on new search strings.
Retain editor position after a failed search.
=> Editor search improvements - revisions to PR #12798

vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
When 'Prompt for Deck' option on a return to Deck trait is selected, then a list of available Decks is provided. You click one, then click the OK or Cancel button.
If you click OK or Cancel without selecting a Deck, you get a NPE.
=> 12765 - Cancelling Return To Deck no longer causes crash

vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Correction to spelling of `indexes`.
=> Spelling correction on Global Options panel

vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java, vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
(Updated) PR now reverts MPL to pre-v3.7.5 behaviour - no Basic Piece line, blank or otherwise.
This PR can supersede, or be merged back into, PR #12997.
=> Fix poor performance of Piece Definer; remove spurious blank line from Mass Piece Loader

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Concepts.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Search.adoc
Search will now, by default, exclude main module contents when in an Extension. An option is provided to include module in the search.
Requires PR #12798.
=> Search: Add option to exclude module elements when editing extension

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java, vassal-app/src/main/java/VASSAL/chat/node/NodeClient.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
This solution pops up a dialog if a non-owner tries to start a new game in an online room and does not start the game.  Not ideal, but manipulating the enabled status of all the different menu options involved is too difficult.
=> 13022 - Prevent room non-owners starting new games

vassal-app/src/main/java/VASSAL/counters/FreeRotator.java, vassal-app/src/test/java/VASSAL/counters/FreeRotatorTest.java
On counter-clockwise free rotations compute the correct final orientation for the *<rotator_name>_Degrees* property. This fixes a bug where both clockwise and counter-clockwise rotations produce the same degrees despite the final facings being on either side of zero degrees.
When a free rotation passes a full rotation, the *<rotator_name>_Degrees* property keeps increasing potentially well past 360 degrees. This commit limits that property to the range 0 to 359 degrees.
The `getRelativeAngle()` function does not properly handle the case where the mouse position is the same as the counter's origin. This commit checks for that case.
The new unit tests demonstrate these issues and confirm the fixes.
Closes #13049
Closes #13050
=> 13049 - Compute correct _Degrees property for free rotations

vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/map/MovementReporter.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Add `pieceCount` to the map auto reporter. Closes #12943
The label is also included in the FormattedExpressionConfigurer such that it appears in the Inserter dropdown.
Also included in this pull request are spelling and grammar corrections in the comments.
=> Add pieceCount to the map auto reporter

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
Creates a property VassalGameFileName (akin to existing read-only properties such as ModuleVersion).
It is set to the file name of the most recent VSAV/VLOG.
Also fixes two issues with managing window title names from the Wizard which would have impeded the PR.
=> Added VassalGameFileName property

vassal-app/src/main/java/VASSAL/build/module/AttachmentManager.java, vassal-app/src/main/java/VASSAL/counters/Attachment.java
Fixes #13289 
When "auto-attach" and "allow attachment to self"
are both enabled and a new piece is dragged onto
an existing stack, the new piece fails to
attach to self.
=> 13336 - Correct issue when auto-attach and allow attachement to self features both enabled

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Piece can be invisible if it has variable visibility calculated inside a prototype
=> 13405 - At-Start Stack positioning tool now expands prototypes before displaying piece

vassal-app/src/main/java/bsh/Primitive.java
Prevents Bad Data in Module errors if Regex happens to look like an Integer.
=> 13360 - Coerce Regular Expression operator arguments to be strings

vassal-app/src/main/java/VASSAL/counters/UsePrototype.java
Similar to the Beanshell expression validator. Highlights when you prototype name doesn't match one in the module.
=> Add a visual validator for Prototype name in Prototype trait

vassal-app/src/main/java/VASSAL/build/module/AttachmentManager.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/counters/Attachment.java
During game load, earlier loaded pieces where quietly dropping attachments to pieces that had not yet been loaded. This fix records those attachments in the AttachmentManager as 'Pending Attachments'. At the end of the game load, prior to any startup GKC's running, the AttachmentManager is called to re-present all Pending Attachements to their owning Attachment traits to re-try the attachment.
=> 13315 - Preserve all attachments across save/load

vassal-app/src/main/java/VASSAL/counters/CalculatedProperty.java, vassal-app/src/main/java/VASSAL/counters/Labeler.java, vassal-app/src/main/java/VASSAL/tools/FormattedString.java
Also re-enabled evaluation of Calculated Properties in GamePiece palettes, but suppresses errors reporting,
=> 13490 - Suppress errors messages from expressions in text Labels during module load, or in Game Palettes.

vassal-app/src/main/java/VASSAL/build/module/PrototypesContainer.java
Turned out the number of Property Change Listeners attached to Prototype Definitions (each firing of a rebuild of the prototype cross-refererence) increased geometrically with the number of prototype definitions that are edited and have their name changed, finally melting down around the 15th edit.
Re-factored the cross-reference rebuild code to not create additional property change listeners.
=> 13393 - Prevent slowdown when editing multiple Prototypes in sequence.

vassal-app/src/main/resources/logback.xml
logback conversionRule conversionClass is deprecated in favor of class.
=> Update logback configuration to prevent messages to console

vassal-doc/src/main/readme-referencemanual/ReferenceManual/Label.adoc
Also, remove Beanshell preference advice as it is not relevant here, except specifically the bit on leading zeros. Generic advice on Beanshell vs Legacy is given in the general section on expressions.
=> Add Beanshell performance health warning to Text Label trait

vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Skips online check if we're only doing a Load Continuation. New Game & loading a Log file remain barred to room guests.
=> Do not subject Continuation file to online restrictions.

vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java, vassal-app/src/main/java/VASSAL/tools/swing/DialogCloser.java
Redrafted #13804 (originally #13710) for a clean 3.7 build.
Testing indicates a performance improvement where Sleep(0) is used to force a screen refresh, at least on a Mac where the 3.7.15 will display a dummy window on the physical screen. This artefact is removed by the revised approach in this PR. The improvement is particularly noticeable on a 2016 MacBook with the C&C Napoleonics module v5.1.
Also, tested independently by a PC Windows user. There the artefact doesn't seem to occur and this change seems to be transparent.
Other changes to the affected components are Javadoc corrections.
=> Sleep() performance improvement 

vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java, vassal-app/src/main/java/VASSAL/build/module/documentation/HelpFile.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalKeyCommands.adoc
Startup GKC help link needs to go via GlobalKeyCommands.html not via Map.html.
=> Fix a bad reference manual link

vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java
Fixing to Zoom to Height on first user attempt. Re-done against 3.7 branch.
Clean build on 3.7 to supercede #13716.
=> Workaround to height zoom issue

vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
Ensures zero getClickCount() is ignored for mouseReleased(). Investigation found that a zero getClickCount() is consistently associated with issue #12480 - the first such event being zero in a "double" event.
See this [post](https://forum.vassalengine.org/t/drag-drop-bug-piece-drops-through-to-an-underlying-window-advice-needed/84754/4?u=marktb1961) for evidence and some discussion of the issue.  Note that the latest evidence belies that the root cause is overlying windows, since a double event may be observed even when only one window is on screen.
The question of why a zero-click event is sometimes generated remains open. However, initial testing in modules where the fault is easily replicated demonstrates a successful workaround even if this is that case.
=> No clicks, no drop!

vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java
Undo bug appears to cause a piece to lose its map reference part way through a menu display. This workaround restores the current map to the piece, allowing the rest of the menu display method to proceed (assuming there's no other critical data corrupted).
=> Reset map on a piece that has lost its way

vassal-app/src/main/java/VASSAL/chat/node/NodeClient.java
Possible null sender solution, providing that sender is never valid as null when sendToOthers() is called. See related issues; presumably the null exception will occur in any of the usage cases.
Usages, for reference:
Query whether a simple "Disconnected." message is enough feedback to prompt the user to re-try connecting to the Vassal server and that no more helpful action is possible.
Also, corrects  spelling error in a parameter name (self contained with a method).
=> Filter out null sender in sendToOthers(Command)

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
Bring forward ModuleGameFileName in response to recent forum request.
This change has been held in the 3.8 queue. I propose it for 3.7 as it has no effect except for a module designer who specifically uses it, and can therefore insist that module users update their version of Vassal.
=> Property ModuleGameFileName makes last opened game file name available to the  current player

dist/macos/Info.plist
Set LSArchitecturePriority to arm64, and change the bundle id to stop the old architecture preference from being cached.
=> Set the Mac bundle to prefer arm64

Makefile
The makeFile currently does not handle having merges from branches with "/" in them such as a branch named features/cool_feature.  If the slashes are not removed from those branch names, subdirectories get created that then break the code. For example at line 191-192:
$(TMPDIR)/VASSAL-$(VERSION)-other.zip: $(TMPDIR)/other-$(VERSION)-build/VASSAL-$(VERSION)
pushd $(TMPDIR)/other-$(VERSION)-build ; zip -9rv ../../$@ VASSAL-$(VERSION) ; popd
Breaks becuase the "../../" part assumes no subdirectories are created by $(VERSION). The code also breaks at 209-210.
I'm surprised this bug hasnt been detected sooner. I recently had to rename I branch I was creating a PR from because of this issue.
Here is part of the log showing the errors caused by keeping slashes in branch name:
```
mkdir -p …
```
=> Bug in Makefile when pulling from branch with "/" in name

dist/macos/Info.plist
Fixes an issue with PR #[13650](https://github.com/vassalengine/vassal/pull/13650) (spurious tag in the Mac plist).
=> Fix mac build

vassal-app/src/main/java/VASSAL/tools/lang/MemoryUtils.java
ManagementFactory.getOperatingSystemMXBean() can throw NPE; there's nothing we can do about that other than catch it.
=> Prevent NPEs when checking for amount of physical memory

vassal-app/src/main/java/VASSAL/tools/LaunchButton.java
Don't display an empty tooltip when pointer hovers over a toolbar button.
Closes #14070
=> 14070 Do not display blank or empty tooltips

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
The menu system prevents the user from clicking 'Begin Logfile' when a log file is already open. Hotkeys were not restricted and could restart the log file. Closes #13682
This change only affects the 'Begin Logfile' command. We could instead replace this check with one in `KeyStrokeListener.keyPressed()` to  prevent the actions of any and all disabled KeyStrokeListeners. Not sure if that is a breaking change and/or desirable. Any thoughts are appreciated.
=> 13682 Prevent Hotkey from restarting an open log file

vassal-app/src/main/java/VASSAL/build/module/turn/CounterTurnLevel.java, vassal-app/src/main/java/VASSAL/build/module/turn/ListTurnLevel.java, vassal-app/src/main/java/VASSAL/build/module/turn/TurnLevel.java, vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java, vassal-app/src/test/java/VASSAL/build/module/turn/CounterTurnTrackerTest.java, vassal-app/src/test/java/VASSAL/build/module/turn/ListTurnTrackerTest.java
The List Turn Tracker has an option to allow players to turn off items in the list. The first and last items in the list do not always honour this flag. When traversing in the forward direction on rollover back the start of the list, the first item is always shown regardless. On a backwards traversal, the item before the first item is always shown (if the index of the first item is zero, it's the last item that's shown).  Hence a one item list cannot be turned off.
Features of this merge request:
1. Skip over consecutive inactive items across multiple lists.
2. Search for and select the first active list item on a forward traversal.
3. Search for and select the last active list item on a reverse traversal.
4. If all items are inactive the list item remains unchanged.
5. Add unit tests to …
=> Fix Turn Counter displaying hidden list items

vassal-app/src/main/java/VASSAL/configure/FormattedStringConfigurer.java, vassal-app/src/main/java/VASSAL/configure/StringConfigurer.java
Noticed this was being looked at and one of those pull requests sparked an idea. Added a check to prevent 'select all' when the focus remains on the same control. Fixed the tab key so that focus actually goes to the next control on the page. Added 'insert key' to expand the dropdown.
Closes #12924
=> 12924 Report format drop down fix 
