src/VASSAL/counters/TriggerAction.java
New Pull Request for By 12973. 
No change to functionality. Use Builder Pattern correctly to allow atomic NullCommands to be replaced by the Command that is being appended.
Reduces clutter and unnecessary complexity in Command Sequence and greatly simplifies debugging.
=> Bug 12973 - Unnecessary NullCommands being generated by Trigger Action

src/VASSAL/counters/SetGlobalProperty.java
Fix incorrect ExpressionConfigurer in Config corrupting property names.
Change ad hoc error reporting to use BadDataReport.
=> Bug 13018. Fix incorrect ExpressionConfigurer in Config.

src/VASSAL/build/module/map/PieceMover.java, src/VASSAL/command/SetPersistentPropertyCommand.java, src/VASSAL/counters/BasicPiece.java, src/VASSAL/counters/Decorator.java, src/VASSAL/counters/Pivot.java, src/VASSAL/counters/ReturnToDeck.java, src/VASSAL/counters/SendToLocation.java, src/VASSAL/counters/Translate.java, src/VASSAL/property/PersistentPropertyContainer.java, src/VASSAL/tools/image/ImageIOImageLoader.java
Been learning a lot about Git :) Have had to this about 4 times, but finally have all the changes for these 2 bugs into a single PR. They are combined because SendToLocation is affected by both.
I've still managed to suck in src/VASSAL/tools/image/ImageIOImageLoader.java by mistake. There was an import I couldn't find.
=> Bugs 12970 12972 final before it drives me mad

src/VASSAL/counters/PieceIterator.java, src/VASSAL/tools/EnumeratedIterator.java, src/VASSAL/tools/IterableEnumeration.java, src/VASSAL/tools/IterableIterator.java, src/VASSAL/tools/IteratorUtils.java, src/VASSAL/tools/ZipUpdater.java, src/VASSAL/tools/io/ZipArchive.java
Minor refactoring that keeps the current API, marking several classes and methods as deprecated.
=> Refactoring - apply modern java standards to enumerations and iterators

src/VASSAL/build/module/map/MenuDisplayer.java, src/VASSAL/chat/CgiServerStatus.java, src/VASSAL/chat/jabber/JabberClient.java, src/VASSAL/tools/icon/IconFactory.java, src/VASSAL/tools/imports/adc2/ADC2Module.java, src/VASSAL/tools/menu/MenuManager.java
Another minor refactoring that simplifies code
=> Refactoring - Use single map method from Java 8

src/VASSAL/counters/Deck.java, test/VASSAL/counters/DeckTest.java, test/VASSAL/counters/StackTest.java
Slightly changed the code in the Deck class, added a first batch of unit tests for the Deck, which are mostly converted from Stack's unit tests.
Also fixed some typos in StackTest.
=> Refactoring Deck

.travis.yml
Well this was quick to setup, I had it running within 5 minutes.
Followed this guide: https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github
Then added the tiny configuration file from this PR, and it worked like a charm: https://travis-ci.com/github/yanlyub/vassal
I understand that this will also detect and build all PRs and comment in the PRs whether they are good to go or break the build.
Generally this is a must have, all the unit tests, compilation of classes, checkstyle rules of the world are worth nothing if they are not ran automatically and at the end of the day it's up to the maintainer to tediously find out what the developers have broken with their PRs.
=> Use Travis CI

src/main/java/VASSAL/tools/io/IOUtils.java, src/test/java/VASSAL/tools/image/tilecache/TileToImageTest.java, src/test/java/VASSAL/tools/io/IOUtilsTest.java, src/test/java/VASSAL/tools/io/TailerTest.java
Write test output to target/test-classes.
=> Fix tests for Windows

src/main/java/VASSAL/configure/PropertiesWindow.java
This appears to fix the problem, from my tests.
=> Bug 13146 - Fix class search to account for custom classes.

src/main/java/VASSAL/counters/Footprint.java
Earlier PR already merged so this is result of the discussion afterwards.
=> 12551b - Back to protected members instead of private

pom.xml
Minor version bump for some of the build tools
=> Upgraded maven-surefire-plugin and checkstyle ruleset to latest versions

Makefile
=> Remove Makefile cruft

CHANGES, Makefile, dist/macosx/Info.plist
Fixed version number and year set incorrectly in Mac DMG's Info.plist.
=> Bug 13152: Version number and year set incorrectly in Mac DMG's Info.plist

pom.xml, src/main/java/VASSAL/build/GameModule.java, src/main/java/VASSAL/build/module/InternetDiceButton.java, src/main/java/VASSAL/build/module/PrivateMap.java, src/main/java/VASSAL/build/module/gamepieceimage/ImageItem.java, src/main/java/VASSAL/build/module/gamepieceimage/ShapeItem.java, src/main/java/VASSAL/build/module/gamepieceimage/SymbolItem.java, src/main/java/VASSAL/build/module/gamepieceimage/TextBoxItem.java, src/main/java/VASSAL/build/module/gamepieceimage/TextItem.java, src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/HexGridNumbering.java, src/main/java/VASSAL/build/module/turn/CounterTurnLevel.java, src/main/java/VASSAL/build/module/turn/ListTurnLevel.java, src/main/java/VASSAL/chat/node/NodeClient.java, src/main/java/VASSAL/configure/PlayerIdFormattedStringConfigurer.java, src/main/java/VASSAL/configure/StringArrayConfigurer.java, src/main/java/VASSAL/counters/Decorator.java, src/main/java/VASSAL/counters/ImagePicker.java, src/main/java/VASSAL/counters/Obscurable.java, src/main/java/VASSAL/counters/ReportState.java, src/main/java/VASSAL/preferences/EnumPreference.java, src/main/java/VASSAL/tools/ArrayUtils.java
* Upgraded to commons-io 2.7.
* Upgraded to commons-coded 1.14.
* Upgraded to commons-lang3 3.10.
* Deprecated ArrayUtils in favor of the one in commons-lang3, now that it duplicates all of the functionality of ours.
=> Bug 13164: Upgrade Apache commons libs

src/main/java/VASSAL/build/module/DieManager.java, src/main/java/VASSAL/counters/SendToLocation.java
Two tiny changes I had lying around
=> Cleanup code

src/main/java/VASSAL/tools/version/GitProperties.java, src/test/java/VASSAL/tools/version/GitPropertiesTest.java, src/test/resources/git-branch-master.properties
Also changed the unit test to use the more readable and generally much better hamcrest asserts.
=> Added branch to version number

src/test/java/VASSAL/tools/version/GitPropertiesTest.java
Tiny upgrade of hamcrest assert
=> Replaced deprecated org.junit.Assert.assertThat

src/test/java/depreport/DepreportFlattener.java, src/test/java/depreport/DepreportRunner.java, src/test/java/depreport/UnusedDependenciesWriter.java, src/test/resources/depreport/deprecated.txt, src/test/resources/depreport/depreport.txt, src/test/resources/depreport/unused-dependencies.txt
Step 1 in resolving http://www.vassalengine.org/tracker/show_bug.cgi?id=13124, a tool that processes the two input files and spits out a new file containing only the unused dependencies.
=> Bug 13124 - added tool to determine unused dependencies

src/main/java/VASSAL/build/module/map/PieceMover.java, src/main/java/VASSAL/counters/Obscurable.java
Per email thread. Fixes a bug introduced by PR#6 but apparently not in 3.3.2.
=> 13186 - Fix deck drawing that allowed drawn card to be seen prematurely

src/main/java/VASSAL/counters/Pivot.java
changed use of Decorator.setOldProperties to undepreciated call with argument in Pivot.java
=> changed use of setOldProperties to undepreciated

src/test/resources/checkstyle-checks.xml
This should help the Eclipse checkstyle plugin to find the suppressions file.
=> Add checkstyle suppression file to checkstyle-checks.xml

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Still left it no key by default, but now it can at least be assigned one.
=> 13172 - Undo button can now be assigned a hotkey by module designer

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/launch/Player.java
This is a follow-up for https://github.com/vassalengine/vassal/pull/104 which didn't make it into the PR anymore.
=> Removed last call to deprecated method, clarified javadoc comment

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/java/VASSAL/launch/EditorWindow.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Reasonably decent search function for Editor. Currently can match "name" or "class name" of any entry in the tree.
Offers toggles for whether names and/or class names are matched.
Offers toggle for "match case"
Open to any suggestions for improving interface & functionality. 
I'm thinking about ways to be able to match the internals of Traits (less about the mechanics of getting stuff out of the traits and more about what the UI flow would be like)
=> 13191 - SEARCH function added to EDITOR (holy crap I can't wait to get to actually use this)

vassal-app/src/main/java/VASSAL/build/module/Inventory.java, vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java, vassal-app/src/main/java/VASSAL/build/module/map/GlobalMap.java, vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java, vassal-app/src/main/java/VASSAL/build/module/map/PieceRecenterer.java, vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java, vassal-app/src/main/java/VASSAL/build/module/map/StackMetrics.java, vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/HexGrid.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/SquareGrid.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/ZoneHighlight.java, vassal-app/src/main/java/VASSAL/command/MoveTracker.java, vassal-app/src/main/java/VASSAL/configure/AutoConfigurer.java, vassal-app/src/main/java/VASSAL/configure/EditPropertiesAction.java, vassal-app/src/main/java/VASSAL/configure/IconConfigurer.java, vassal-app/src/main/java/VASSAL/configure/SavedGameUpdaterDialog.java, vassal-app/src/main/java/VASSAL/launch/TilingHandler.java, vassal-app/src/main/java/VASSAL/preferences/PositionOption.java, vassal-app/src/test/resources/checkstyle-checks.xml
Fixes a bunch of checkstyle warnings.
=> Code formatting

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/GpIdChecker.java, vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java, vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java, vassal-app/src/main/java/VASSAL/build/module/PrototypeDefinition.java, vassal-app/src/main/java/VASSAL/build/module/PrototypesContainer.java
Updated with suggestions, based on latest source
=> Bug 13178 - GameRefresher fixes - Version 2

vassal-app/src/main/java/VASSAL/build/module/Inventory.java, vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java, vassal-app/src/main/java/VASSAL/counters/ActionButton.java, vassal-app/src/main/java/VASSAL/counters/BasicPiece.java, vassal-app/src/main/java/VASSAL/counters/Decorator.java, vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java, vassal-app/src/main/java/VASSAL/counters/KeyBuffer.java, vassal-app/src/main/java/VASSAL/counters/KeyCommand.java, vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java, vassal-app/src/main/java/VASSAL/counters/PropertyExporter.java, vassal-app/src/main/java/VASSAL/counters/ReportState.java
Walking on ice here with all the downcasting and relying on Vassal veterans' experience, is this roughly what was proposed in http://www.vassalengine.org/forum/viewtopic.php?f=5&t=11964#p61060?
=> Bug 13229: Save property map instead of piece clone as snapshot

vassal-app/src/main/java/VASSAL/configure/BeanShellExpressionConfigurer.java, vassal-app/src/main/java/VASSAL/configure/BeanShellFunctionMenu.java, vassal-app/src/main/java/VASSAL/counters/CalculatedProperty.java, vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java, vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java, vassal-app/src/main/java/VASSAL/script/expression/BeanShellExpression.java, vassal-app/src/main/java/VASSAL/script/expression/Expression.java, vassal-app/src/main/java/VASSAL/script/expression/ExpressionBuilder.java, vassal-app/src/main/java/VASSAL/script/expression/FunctionBuilder.java, vassal-app/src/main/java/bsh/BeanShellExpressionValidator.java, vassal-app/src/main/resources/VASSAL/script/init_expression.bsh
- Add ? to Expression Builder
- Add existing Java Math functions to Expression Builder
- Add existing Java String functions to Expression Builder
- Create random and isRandom functions and add to Expression Builder
- Create Sum and Count functions and add to Expression Builder
- Add additional 'hints' that can be displayed below function input in Expression Builder
- Clean up PieceDefiner to Java 11 standards
=> Expression Builder/Beanshell improvements

vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java, vassal-app/src/main/java/VASSAL/counters/BasicPiece.java, vassal-app/src/main/java/VASSAL/counters/KeyBuffer.java
Now done The Better Brent Way (tm). To prevent module designer from failing to implement part of the feature and therefore experiencing the false illusion of success.
See commentary in #134
=> 13218 Better method for getting ClickedX and ClickedY passed through

vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java
(in all our hanky panky earlier a special case got lost I guess)
=> Bug 13239: Right-click doesn't pick up whole stack anymore

vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java, vassal-app/src/main/java/VASSAL/counters/Embellishment.java, vassal-app/src/main/java/VASSAL/counters/Immobilized.java, vassal-app/src/main/java/VASSAL/counters/PieceCloner.java, vassal-app/src/main/java/VASSAL/tools/imports/adc2/MapBoard.java
This is some preparatory work for flattening property access. It is not intended to produce any behavior changes.
=> Property access cleanup

vassal-app/src/main/java/VASSAL/Info.java, vassal-app/src/main/java/VASSAL/tools/BugUtils.java, vassal-app/src/main/java/VASSAL/tools/HTTPPostBuilder.java
See http://www.vassalengine.org/tracker/show_bug.cgi?id=13259 for an example.
Also fixes the missing '"' in HTTPPostBuilder.
=> Issue 13251 - Add Module name to Bug summary, extra info to comments

vassal-app/src/main/java/VASSAL/tools/DataArchive.java, vassal-app/src/main/java/VASSAL/tools/ProblemDialog.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Small re-org of strings and 6 months worth of deprecation comments to the Chatter.
=> Deprecation warning to Chat Window for first 6 months

vassal-app/src/main/java/VASSAL/tools/KeyStrokeListener.java, vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
Fixes issue from forums today.
=> Bug 13280: Null protection in key translators

pom.xml, release-prepare/pom.xml, vassal-app/pom.xml, vassal-app/src/main/java/VASSAL/tools/SequenceEncoder.java, vassal-app/src/test/java/VASSAL/tools/SequenceEncoderTest.java, vassal-doc/pom.xml
This improves SequenceEncoder performance by around 5% when creating save game strings.
=> SequenceEncoder optimizations

pom.xml, vassal-app/pom.xml, vassal-deprecation/pom.xml, vassal-deprecation/src/main/java/org/vassalengine/deprecation/DeprecationProcessor.java
The interesting part of the build log starts here: https://travis-ci.com/github/vassalengine/vassal/builds/179198137#L271
=> Vassal deprecation system

vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
Emergency fix to PieceSlot to allow modules to load.
=> Emergency bug fix - Unable to load any modules

vassal-app/src/main/java/VASSAL/configure/PropertyExpression.java, vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java, vassal-app/src/test/java/VASSAL/counters/TriggerActionTest.java
1. Fix missing $$ handling in Sum and Count BeanShell functions
2. Restore broken legacy $$ handling in non-GKC property match expressions
This is the first of my beta-1 bugs I need to fix. GameRefresher issue to come.
=> Beta-1 Issue 13291 - Beanshell issues with $$ variable processing

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
That method did the opposite of what it looks like.
=> 13217: Fix editor cut-and-paste issue

vassal-app/src/main/java/VASSAL/build/module/GameState.java
13332 Buffer Save Game writing to improve performance
=> 13332: Improve save game write time

vassal-app/src/main/java/VASSAL/build/AbstractBuildable.java, vassal-app/src/main/java/VASSAL/build/AbstractConfigurable.java, vassal-app/src/main/java/VASSAL/build/Buildable.java, vassal-app/src/main/java/VASSAL/build/Builder.java, vassal-app/src/main/java/VASSAL/build/Configurable.java, vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/command/Command.java, vassal-app/src/main/java/VASSAL/command/CommandEncoder.java, vassal-app/src/main/java/VASSAL/i18n/Translatable.java, vassal-app/src/main/java/VASSAL/tools/SequenceEncoder.java
If this seems like a good direction to head, I'll do more.
=> Javadoc improvements for some abstract classes

vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Previously players could switch sides w/ little transparency. This isn't foolproof of course but it's good transparency.
Also cleaned up various little code nubbins.
=> 13323 - Player switching sides now reported in Chat Log

vassal-app/src/main/java/VASSAL/Info.java, vassal-app/src/main/java/VASSAL/tools/version/VassalVersionTokenizer.java, vassal-app/src/main/java/VASSAL/tools/version/VersionFormatException.java, vassal-app/src/main/java/VASSAL/tools/version/VersionTokenizer.java, vassal-app/src/main/java/VASSAL/tools/version/VersionUtils.java, vassal-app/src/test/java/VASSAL/InfoTest.java, vassal-app/src/test/java/VASSAL/tools/version/VassalVersionTokenizerTest.java, vassal-app/src/test/java/VASSAL/tools/version/VersionUtilsTest.java
Updated version checks. Added version check tests.
=> Updated version checks

vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
Refactored complicated case in PlaceMarker.placeMarker().
=> 2377 NPE in Decorator.getOutermost() caused by PlaceMarker

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
=> Add a chatter message when starting to write a logfile

vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Modified method EnsureVisible. Chenged behaviour, instead of showing a rectangle with the moved piece on one of the edges, it will show a rectangle so that the piece moved is in the center.
In addition the centering on opponent move will be triggered by a unit that is already visible by the opponent but that moves "too close" to the border of the visible area. 
For the moment "Too close" is defined as a band around the edges of 5% of the height or width of the visible rectangle.
=> 13355: changes to EnsureVisible method map.java

vassal-app/src/main/java/VASSAL/build/GpIdChecker.java, vassal-app/src/main/java/VASSAL/build/GpIdSupport.java, vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java, vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
=> 13329: Don't create new GpID's for temporary pieceslots

vassal-app/src/main/java/VASSAL/build/AbstractBuildable.java, vassal-app/src/main/java/VASSAL/build/module/Map.java
The neverending javadoc project continues, with Map.java coming under the microscope
=> Javadoc3 - MAP! 

vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java, vassal-app/src/main/java/VASSAL/counters/Deselect.java, vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
There have been requests for the ability to deselect pieces w/ a key command. This implements that in a nice little trait. Optionally the deselected piece can also be popped out of its stack (useful when what you're doing is "dropping a piece off" from a moving stack). 
Provides all the normal trait features, and I have provided localization hooks.
If approved I'll provide the documentation.
=> 13297 - Deselect - way to cause deselection and stack-removal for a specific piece.

vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java, vassal-app/src/main/java/VASSAL/counters/Decorator.java, vassal-app/src/main/java/VASSAL/counters/Pivot.java, vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java, vassal-app/src/main/java/VASSAL/counters/SendToLocation.java, vassal-app/src/main/java/VASSAL/counters/Translate.java
Added new putOldProperties() sig, changed all Vassal code, Deprecated original calls.
=> 3.4.1 - 13376 - Reverted changed setOldProperties call sigs. 

vassal-app/src/main/java/VASSAL/build/module/Chatter.java
Should hopefully reduce "flickering" of the chatter, though I'd like to get Claudio to test since he had a good repro case.
=> 13389: Make Chatter less flickery

vassal-app/src/main/java/VASSAL/configure/ColorConfigurer.java, vassal-app/src/test/java/VASSAL/configure/ColorConfigurerTest.java
Fix for bug 13307: http://www.vassalengine.org/tracker/show_bug.cgi?id=13307
=> added saving/reading of transparency for color backgrounds

pom.xml, vassal-app/pom.xml, vassal-doc/pom.xml
- commons-codec: https://commons.apache.org/proper/commons-codec/changes-report.html#a1.15
- commons-io: http://commons.apache.org/proper/commons-io/changes-report.html#a2.8.0
- mockito: https://github.com/mockito/mockito/blob/release/3.x/doc/release-notes/official.md
=> Updated dependencies, pom.xml cleanup

vassal-app/src/main/java/VASSAL/build/module/Map.java
=> bug13409 fix board.SnapTo error by calling it again

vassal-app/src/main/java/VASSAL/build/module/Chatter.java
Apparently we DO need the update. "Sometimes".
See http://www.vassalengine.org/forum/viewtopic.php?f=3&t=12364&p=63953#p63953
=> 3.4.2(!!) - 13416 - fix chatter not updating

vassal-app/src/test/java/VASSAL/counters/PropertiesPieceFilterTest.java, vassal-app/src/test/java/VASSAL/script/ExpressionInterpreterTest.java
(Legacy Property Match Expressions)
=> 3.4.2-13425 Unit Tests for PropertiesPieceFilter 

vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
made it a preference and set default at 60 (was hardcoded at 30 before)
=> 3.5 - 13368 - preference to control drag-at-edge-of-map width

vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
=> 3.4.3 - 13433 - Card draw facing revisited

vassal-app/src/main/java/VASSAL/Info.java
Snapshot couldn't find its errorLog file because of version number truncation.
=> errorLog - so it will work in snapshots and stuff

vassal-app/src/main/java/VASSAL/build/module/map/LOS_Thread.java
=> 3.5 - Restore lost LOS_Thread localization "PART DEUX"

vassal-app/src/test/java/VASSAL/counters/PropertiesPieceFilterParameterizedTest.java, vassal-app/src/test/java/VASSAL/counters/PropertiesPieceFilterTest.java
Merge existing PropertiesTestFilter tests into @Flints parameterized tests. Add additional tests.
=> insert formatting

vassal-app/src/main/java/VASSAL/build/GameModule.java
Added back ChatServerFactory key for jabber in case anyone still has it sitting around.
=> Remap jabber key to official server

CHANGES
Clarifies what we actually added
=> 3.5 - more accurate changelist entry (we added search in 3.4.0)

vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java, vassal-app/src/main/java/VASSAL/chat/SoundEncoder.java, vassal-app/src/main/java/VASSAL/command/PlayAudioClipCommand.java, vassal-app/src/main/java/VASSAL/configure/SoundConfigurer.java, vassal-app/src/main/java/VASSAL/counters/PlaySound.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
As requested, here is a "Mute All Sounds" preference :)
I'm guessing this might already have an issue number, back in the mists of time?
=> 3.5 - 1804 - Sound "Mute All" preference

vassal-app/src/main/java/VASSAL/launch/TilingHandler.java
=> "Fix Irritating Thing" Oh Jesus Yes I can Feel it PR 400 COMING RIGHT UP!!!!!!!!!!!!!!!!

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/Chatter.java, vassal-app/src/main/java/VASSAL/tools/QuickColors.java, vassal-app/src/main/java/VASSAL/tools/image/LabelUtils.java
The QuickColors processing moved to a central location for maintainability & convenience adding to more things as appropriate in the future.
=> 3.5 QuickColors refactor

vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Map.adoc was not displaying tables and images correctly
=> RepairMapAdoc

vassal-app/src/main/java/VASSAL/configure/ConfigurerLayout.java, vassal-app/src/main/java/VASSAL/configure/ConfigurerPanel.java, vassal-app/src/main/java/VASSAL/configure/IconConfigurer.java
Fixes an NPE and fixes some weird resizing behavior
=> Fix IconConfigurer issues

vassal-app/src/main/java/VASSAL/configure/TranslatingStringEnumConfigurer.java, vassal-app/src/main/java/VASSAL/counters/BasicPiece.java, vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java, vassal-app/src/main/java/VASSAL/counters/Replace.java, vassal-app/src/main/java/VASSAL/counters/TraitConfigPanel.java, vassal-app/src/main/java/VASSAL/counters/UsePrototype.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/test/java/VASSAL/counters/DecoratorTest.java, vassal-app/src/test/java/VASSAL/counters/PlaceMarkerTest.java, vassal-app/src/test/java/VASSAL/counters/ReplaceTest.java, vassal-app/src/test/resources/clirr-ignored-differences.xml
regularised Properr casing of config messages.
=> 3.5 14450 Configs Ongoing - Place Marker / Replace / 

vassal-app/src/main/java/VASSAL/configure/TextConfigurer.java, vassal-app/src/test/resources/pmd.xml
Other two are in eminently subclassable things, alas.
=> Final static - only nailed one of these. 

vassal-app/src/main/java/VASSAL/build/module/Inventory.java, vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java, vassal-app/src/test/resources/pmd.xml
This turns the rule on, by //NOPMD ing the last two things.
=> Fixed Rest of Final Static

vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/HexGridNumbering.java, vassal-app/src/main/java/VASSAL/launch/ModuleManager.java, vassal-app/src/main/java/VASSAL/tools/imports/adc2/ADC2Module.java, vassal-app/src/test/resources/pmd.xml
//NOPMD the last stragglers so we can turn on the rule
=> Let's Turn This Shit ON!

vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceImage.java, vassal-app/src/test/resources/pmd.xml
Looks like a "different meaning of getInstance()" in this one case.
=> No Instance For YOU! Come Back One Year.

vassal-app/src/main/java/VASSAL/build/module/Inventory.java
(Can be 3.4.8, or punt to 3.5)
=> 3.4.8 - 13449 - Inventory window no longer stays visible after game closed from menu

vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java, vassal-app/src/main/java/VASSAL/counters/PlaySound.java, vassal-app/src/main/java/VASSAL/counters/PropertySheet.java, vassal-app/src/main/java/VASSAL/counters/SimplePieceEditor.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
There were a few last files in VASSAL.counters that didn't have localization keys and //NON-NLS markers in them.
=> 3.5 - Some remaining loc cleanup

vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
Fix 'launch' field shenanigans
=> 3.5 - 13594 - Yay, I Broke Master!!! (This should fix it)

vassal-app/src/main/java/VASSAL/counters/Embellishment.java, vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
13379 - Mass Piece Loader - Base Image can now be loaded into layers
13379 - Mass Piece Loader - Decrease key now loads correctly
13379 - Mass Piece Loader - Layers are no longer loaded Activated
=> 13379 - Mass Piece Loader - Bug fixes

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java
Amazingly less horrible-looking than I thought this was going to be.
=> 3.5 - Fix the Chatter/Palette docking order problem

.gitignore, vassal-app/src/main/java/VASSAL/build/AbstractBuildable.java, vassal-app/src/test/java/VASSAL/build/AbstractBuildableTest.java
Use this branch for my bugfix for 554.
Only tiny fix and tiny test this time
=> 13636: fixes and test for bug 554

vassal-doc/src/main/readme-referencemanual/ReferenceManual/PieceWindow.adoc
Reviewed Game Piece Palette doc + mention that Game Pieces cannot be created at top level
=> Game Piece Palette doc update

bootstrap.sh
Ask for specific JDK version. Upgrade to 15.0.1+9.
=> 13760 - Upgrade to 15.0.1+9

vassal-app/src/main/java/VASSAL/build/module/ChessClockControl.java
Watching its pendulum swing to and fro
=> 13775 - ChessCock - borrowed the L to put in htmL

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java
This one is for 3.4.12 -- merge this one to 3.4.12 and the other to 3.5.
=> 13808 - Don't ask to start log before finished replaying current one

vassal-app/src/main/java/VASSAL/launch/TilingHandler.java
=> Reinstated removed TilingHandler ctor for VASL

vassal-app/src/main/java/VASSAL/build/module/Map.java
=> 13853 - Ensure that the toolbar is made visible (or hidden) along all paths in Map.setup()

vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java, vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java, vassal-app/src/test/resources/clirr-ignored-differences.xml
Minor visual cleanup
Double-click now add trait
=> 13900 - Mass Piece Loader uses correct Layer trait

vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java
Don't immediately reject files which have no extension metadata when loading an extension, since new extensions also lack metadata.
=> 13971 - Make new extensions openable again

vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
Sanitize temp filename bases. Windows has quite a few characters whichare prohibited in filenames.
=> 13996 - Sanitize temp filename bases

vassal-app/src/main/java/VASSAL/preferences/Prefs.java
FileChannel.lock() throws when _this_ process already holds the lock, rather than blocking until the lock can be acquired. So we have to synchronize on the Prefs object first to prevent that.
=> 14000 - Ensure that this process doesn't already have the prefs file lock when we try to take it

vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java, vassal-app/src/main/java/VASSAL/configure/RemoveUnusedImagesDialog.java, vassal-app/src/main/java/VASSAL/counters/TraitLayout.java, vassal-app/src/main/java/VASSAL/launch/EditorWindow.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/test/resources/clirr-ignored-differences.xml
14011 - Pre select search text when dialog opens
=> 14009 - Dialog cosmetic updates

vassal-app/src/main/java/VASSAL/build/module/metadata/AbstractMetaData.java, vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
o Add Date Last Saved Column
o Hide Vassal Version and Date Saved by default, preference to turn on
o Save Column Widths in preference
=> 14019 - Module Manager changes

vassal-app/src/main/java/VASSAL/counters/SetGlobalProperty.java
Makes this part be included in the trait list display
=> 14055 - trait list

vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java, vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java, vassal-app/src/main/java/VASSAL/launch/EditorWindow.java, vassal-app/src/main/java/VASSAL/launch/ModuleEditorWindow.java, vassal-app/src/test/resources/clirr-ignored-differences.xml
Bug 14064
Adds Refresh Predefined Setups to ExtensionEditor 
+ calcel warinings on DoNoT Stack without parent
=> 14064 - RefreshPredefinedSetups in Extension Editor

vassal-app/src/main/java/VASSAL/build/module/properties/PropertyChangerConfigurer.java, vassal-app/src/main/java/VASSAL/configure/StringArrayConfigurer.java, vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
After taking it all apart and putting it back together, the fixed turned out to be fairly simple.
=> 14112-Dynamic Property List of Values cursor jumps after typing 1 character

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/java/VASSAL/configure/EditPropertiesAction.java
14148 - Add feature to track edited components in Module Editor
=> 14148 - Fix truncated labels in Module Editor

vassal-app/src/main/java/VASSAL/counters/KeyCommand.java, vassal-app/src/main/java/VASSAL/counters/TriggerAction.java
Add KeyCommand constructor that admits both enable and TranslationPiece
Pass the TriggerAction piece as translation for KeyCommand
=> 14196 - Fix translation of right-click elements.

vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Fix this by using the i18n string
=> 14200 - Scenario names (Predefined Setup) displayed always in English

vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
LocalizedPieceName
LocalizedBasicName
=> 14207 - Localized Piece Names exposed to Beanshell for creating display strings

vassal-app/src/main/java/VASSAL/build/module/Inventory.java
Fix inventory text translation
=> 14199 - Inventory text not translated

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java, vassal-app/src/main/java/VASSAL/chat/ui/ChatServerControls.java
=> 14226 - UNDO and SERVER buttons no longer start stealing focus from main window after they are clicked

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/build/module/Inventory.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java, vassal-app/src/main/java/VASSAL/build/widget/WidgetMap.java
(Since we had to revert the old version...)
This suppresses "UI-Fidgeting" by e.g. Map windows during the load-game-over-top-of-game process.
=> "Smooth" version of Load Game-or-Log

vassal-app/src/main/java/VASSAL/build/module/GameState.java
Reverts the key bit of this for now. I can see if I can improve in the future.
=> Wipe old game before loading save

vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
It was making -< instead of -> in the auto report defaults
=> 14255 - minor text/html fix

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java
Be a bit more paranoid about reseting the `GameModule` on `GameState.setup()`.
=> Clean up listeners harder

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/Console.java, vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Fixes the bug reported here: http://www.vassalengine.org/forum/viewtopic.php?f=3&t=13150&start=15
Has been a bug since 3.5.0
=> 14351 - don't crash with no Player Roster

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Per forum discussion here - I basically just implemented Mark's suggestion:
http://www.vassalengine.org/forum/viewtopic.php?p=67213#p67213
=> 3.6 - 14360 - Window title less verbose on subwindows

vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java, vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
=> 3.6 - 14257 - option to reverse order pieces are displayed in CounterDetailViewer

vassal-app/src/main/resources/help/Intro.html
Fixed a typo. Made a sentence more accurate.
=> Minor docs corrections

vassal-app/src/main/java/VASSAL/counters/Deck.java
First reported here: http://www.vassalengine.org/forum/viewtopic.php?f=4&t=12782
=> 3.6 - 14346 - Deck reports suppressed during GKC report suppresssion

vassal-app/src/main/java/VASSAL/build/module/Inventory.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Requested on forums - http://www.vassalengine.org/forum/viewtopic.php?f=4&t=12755
=> 3.6 - 14376 - Inventory window allows a hotkey for Refresh

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
So you don't always end up with it all the way at the bottom of your 500 at-start stacks or your 100 global properties or your 90 prototypes!
=> 3.6 - 14372 - OH BLESSED DAY! Duplicate a copy of component 'in place' in editor!

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/java/VASSAL/configure/ExtensionTree.java
1. Grab your favorite module components and just DRAG their sorry asses to a new location!
2. OR, Ctrl+Drag ("That's Cmd+Drag on Mac") to make a FREE copy!
3. PROFIT!!!
=> 3.6 - 14373 - (and 1944!) - HELL YES! Drag-and-drop for Editor items.

vassal-app/src/main/java/VASSAL/build/module/NotesWindow.java
=> 3.5.6 - 14271 - notes window is a keystrokesource so that it won't "eat" keys

vassal-app/src/main/java/VASSAL/configure/BooleanConfigurer.java, vassal-app/src/main/java/VASSAL/preferences/PrefsEditor.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Align checkboxes in center of line
Add missing ? in Boolean options
=> 14388-Add Scrollbars to Prefs Dialog when needed.

vassal-app/src/main/java/VASSAL/build/GpIdChecker.java
=> 14422 - 3.5.6

vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java, vassal-app/src/main/java/VASSAL/counters/Embellishment.java, vassal-app/src/main/java/VASSAL/counters/NonRectangular.java, vassal-app/src/main/java/VASSAL/tools/SequenceEncoder.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Layer.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/NonRectangular.adoc
Layer (Embellishment) and Non-Rectangular gain a "Scale" factor field, applied in addition to any zoom. 
This allows spot adjustments of scale between pieces supplied e.g. in different original sizes.
=> 14464 - Scaling factors for Layers and Non-Rectangular

vassal-app/src/main/java/VASSAL/counters/CalculatedProperty.java
Got bored. Decided to fix random old bug. Found this one.
=> 10755 - Don't infinite loop while reporting one

vassal-app/src/main/java/VASSAL/counters/MatCargo.java
Also I love creating merge conflicts with my other PRs, so that I can enjoy resolving them.
=> Updated comments in MatCargo.java

vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
See: http://www.vassalengine.org/forum/viewtopic.php?p=68180#p68180
=> 14477 - MouseoverStackViewer show a single card when used in Player Hand Window

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/Documentation.java, vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/PrototypesContainer.java, vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/ColorManager.java, vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/FontManager.java, vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceImageDefinitions.java, vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceLayoutsContainer.java, vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java, vassal-app/src/main/java/VASSAL/build/module/map/HighlightLastMoved.java, vassal-app/src/main/java/VASSAL/build/module/map/LayeredPieceCollection.java, vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java, vassal-app/src/main/java/VASSAL/configure/MandatoryComponent.java, vassal-app/src/main/java/VASSAL/configure/SingleChildInstance.java, vassal-app/src/main/java/VASSAL/configure/ValidationReportDialog.java, vassal-app/src/main/java/VASSAL/i18n/Localization.java, vassal-app/src/main/java/VASSAL/script/ScriptContainer.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
- Fixed broken Checks
- Added additional Single Instance checks where needed
- Neatened up report dialog
- Run Validity Check on module load (Player as well as Editor) and report issues in errorlog
=> 14238 Improve Validity Checking

vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java, vassal-app/src/main/java/VASSAL/configure/AutoConfigurer.java, vassal-app/src/main/java/VASSAL/counters/Deck.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
=> 9973 - Deck supports configurable strings for Draw Multiple, Draw Specific, Face Up, Face Down

vassal-app/src/main/java/VASSAL/counters/BasicPiece.java, vassal-app/src/main/java/VASSAL/counters/Delete.java, vassal-app/src/main/java/VASSAL/counters/Mat.java, vassal-app/src/main/java/VASSAL/counters/MatCargo.java, vassal-app/src/main/java/VASSAL/counters/Replace.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mat.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/MatCargo.adoc
(Following an Almoravid stress dream last night I awoke with a vision of exposing more properties)
This PR adds on to an already-new 3.6 feature, and so is either its own ticket, or doesn't need a ticket since it's just part of "Mats"
=> Some additional useful properties for Mats and Mat Cargo, along with documentation

vassal-app/src/main/java/VASSAL/build/module/Map.java
=> 10390 NPE in GameModule loading module after deleting Map from Chart Map

vassal-app/src/main/java/VASSAL/preferences/BasicPreference.java, vassal-app/src/main/java/VASSAL/preferences/BooleanPreference.java, vassal-app/src/main/java/VASSAL/preferences/DoublePreference.java, vassal-app/src/main/java/VASSAL/preferences/EnumPreference.java, vassal-app/src/main/java/VASSAL/preferences/IntegerPreference.java, vassal-app/src/main/java/VASSAL/preferences/StringPreference.java, vassal-app/src/main/java/VASSAL/preferences/TextPreference.java
This is the correct fix for #10351
=> 10351 Global Options custom preferences not always initialised

vassal-app/src/main/java/VASSAL/chat/HttpRequestWrapper.java
=> Reinstate inadvertently removed null check for props

vassal-app/src/main/java/VASSAL/tools/BrowserSupport.java
* Pages sometimes load on Linux only after Vassal is closed.
* Fall back to 'open' on MacOS.
* Fall back to 'start' on Windows.
=> Improved browser launch support

vassal-app/src/main/java/VASSAL/counters/BasicPiece.java, vassal-app/src/main/java/VASSAL/counters/Decorator.java, vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/MatCargo.adoc
Thought of a good use for "Old" versions of these two properties, so added them!
=> 10578 - MatCargo now provides OldMatOffsetX and OldMatOffsetY properties

vassal-app/src/main/java/VASSAL/chat/PrivMsgCommand.java, vassal-app/src/main/java/VASSAL/chat/ui/PrivateMessageAction.java
=> 5493 - Private chat windows will no longer steal focus

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
#4381 OLDEST BUG IN THE BOOK!!!
I might play with adding similar displays to the Define Shape for Zone, etc.
=> 4381 - Show X,Y in Configurer when e.g. repositioning Stack

vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
=> 10115 - Fixed corner-case NPE when closing a game

vassal-app/src/main/java/VASSAL/chat/PrivMsgCommand.java, vassal-app/src/main/java/VASSAL/chat/PrivateChatManager.java, vassal-app/src/main/java/VASSAL/chat/PrivateChatter.java, vassal-app/src/main/java/VASSAL/chat/ui/PrivateMessageAction.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
=> 6024 Private Message windows no longer prompt to ignore every time you close them. Incoming private messages do not grab focus.

vassal-app/src/main/java/VASSAL/build/module/map/StackMetrics.java, vassal-app/src/main/java/VASSAL/counters/Stack.java
=> 10333 - Fix occasional draw-side exceptions during loading game and saving screenshots.

vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Label.adoc
=> 6557 - Better documented pieceName vs PieceName

vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java, vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java, vassal-app/src/main/java/VASSAL/counters/CounterGlobalKeyCommand.java, vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java, vassal-app/src/main/java/VASSAL/tools/imports/adc2/ADC2Module.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalKeyCommand.adoc
=> 9981 - Global Key Commands - "Within a Deck, select Fixed number of pieces" field now supports expressions

vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
ANOTHER ALMORAVID BUG EXPLAINED!!!!!!!!
=> 10711 - When rotating a mat, jointly rotating cargo should prefer to stay with current mat

vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
(tried to describe what we wanted a bit better)
=> 5489 - Improved bug dialog text

vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/test/resources/clirr-ignored-differences.xml, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Hideable.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Layer.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/MarkMoved.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mask.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/MovementTrail.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/NonStacking.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/PieceWindow.adoc
@uckelman Note this "add fields to deck" -- one rescued from staticness, and the other added.
=> 10691 - Mouseover Stack Viewer - Unstatic a naughty field in CounterDetailViewer, and add ability to count face down cards in a deck

vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java, vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java, vassal-app/src/main/java/VASSAL/counters/Deck.java, vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Initial structure and configurers all put together - it just doesn't seem to be restricting access correctly
=> Deck access - allow access to decks to be restricted by player

vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java, vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
DGKCs turned out to roll their own "accept" so needed to be updated to the new expressions. 
The bug never made it into a beta, so doesn't need changelist.
=> Unbreak DGKC

vassal-app/src/main/java/VASSAL/build/AbstractFolder.java, vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java, vassal-app/src/main/java/VASSAL/build/Widget.java, vassal-app/src/main/java/VASSAL/build/module/ChartWindow.java, vassal-app/src/main/java/VASSAL/build/module/ChessClockControl.java, vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/NotesWindow.java, vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java, vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java, vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java, vassal-app/src/main/java/VASSAL/build/module/PrototypeDefinition.java, vassal-app/src/main/java/VASSAL/build/module/SpecialDiceButton.java, vassal-app/src/main/java/VASSAL/build/module/chessclockcontrol/ChessClock.java, vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java, vassal-app/src/main/java/VASSAL/build/module/map/Flare.java, vassal-app/src/main/java/VASSAL/build/module/map/LayerControl.java, vassal-app/src/main/java/VASSAL/build/module/map/LayeredPieceCollection.java, vassal-app/src/main/java/VASSAL/build/module/turn/TurnComponent.java, vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java, vassal-app/src/main/java/VASSAL/build/widget/BoxWidget.java, vassal-app/src/main/java/VASSAL/build/widget/Chart.java, vassal-app/src/main/java/VASSAL/build/widget/HtmlChart.java, vassal-app/src/main/java/VASSAL/build/widget/ListWidget.java, vassal-app/src/main/java/VASSAL/build/widget/MapWidget.java, vassal-app/src/main/java/VASSAL/build/widget/PanelWidget.java, vassal-app/src/main/java/VASSAL/build/widget/TabWidget.java, vassal-app/src/main/java/VASSAL/configure/ComponentDescription.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
=> 9635 - Add description fields to most important editor components

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java, vassal-app/src/main/java/VASSAL/launch/PlayerWindow.java, vassal-app/src/main/java/VASSAL/tools/DebugControls.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Starting to work on a little doodad, with the initial main goal of being able to find out X/Y positions easily. 
Removed default hotkey but you can add one in GlobalOptions.
Meanwhile it now appears on the Tools menu for the Player.
=> Module "Debug" Window

vassal-doc/src/main/readme-referencemanual/ReferenceManual/PlayerHand.adoc
Per @riverwanderer at https://forum.vassalengine.org/t/documentation-suggested-update-to-player-hand-section-of-reference-manual/72942
=> 10751 - Better description of Player Hand

vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
(FIXME markers on something that wasn't broken)
=> 9206 - remove incorrect FIXME markers 

vassal-app/src/main/java/VASSAL/build/module/map/MoveCameraButton.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Ability to zoom the camera when moving it was immediately requested in forums
=> 10749 - Move Camera Button can also change Zoom

vassal-app/src/main/java/VASSAL/build/module/PrivateMap.java
=> 9487 - When switching sides, close private hands/windows that we no longer have access to.

vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Server text wording improvements, per Mark Benson. Text only.
=> 10764 - Server text improvements

vassal-app/src/main/java/VASSAL/build/module/map/LOS_Thread.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
It's funny when I find one of these from 2009 and it takes like 5 minutes to do ;) 
The 3-pixel-wide looks so good it's tempting to make it the default...
Fixes #4391
=> 4391 - LOS thread thickness is adjustable

vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java, vassal-app/src/main/java/VASSAL/counters/KeyBuffer.java
=> 4479 - Can Shift+Click and Ctrl+Click on Game Piece Palette, allowing groups of pieces to be dragged onto the map.

vassal-app/src/main/java/VASSAL/counters/Immobilized.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/NonStacking.adoc
Mark asked for this. No more of a key conflict than any of the others already are...
#10007
=> 10007 - Ctrl/Cmd to select for Does Not Stack

vassal-app/src/main/java/VASSAL/launch/ModuleManager.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
=> 5569 - Preference to turn off automatic update notification

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-doc/src/main/designerguide/maps-and-boards.adoc
* Cleanup work on the isVisible fix
* DrawingMouseoverIndex to dramatically speed up certain boundingbox/draw checks. If I'd known about this before I'd have _only_ exposed this instead of the boolean, but that binary ship has sailed.
=> Profiling stuff

vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
=> 10795 - protect against no available trait being yet selected

vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
1. Sorting of Dice while keeping reported 0's as kept rolls.
2. Changed in numbers of dice kept did not clear out old $resultn$ values.
=> 10814 Fix Dice Button reporting when Keeping and Sorting results

vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
@riverwanderer had a few text tweak suggestions for the server stuff.
=> 10834 - (Text only) Server text tweaks

vassal-app/src/main/java/VASSAL/counters/Replace.java, vassal-app/src/main/java/VASSAL/counters/SetGlobalProperty.java
=> 10850 - Display proper name for Set Global Property and Place Marker

vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
=> 10883 - Wasn't possible to click add to add an Action Button trait to a piece.

vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java, vassal-app/src/main/java/VASSAL/configure/StringConfigurer.java
The default lenghth is the longhthest lenghth there is.
=> Fixed typo

vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
Fixes: https://github.com/vasl-developers/vasl/issues/1054
=> 10908 - Fix NPE send-to-locationing backwards

vassal-app/src/main/java/VASSAL/command/MovePiece.java, vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
=> Repair some undo bugs in MovePiece

vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
Apparently I only half-fixed it before.
=> SendToLocationNPEFix

vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java, vassal-app/src/main/java/VASSAL/command/MovePiece.java
Fixes #10925 
Because if you _let_ them set the size to zero...
=> 10925 - Turn Tracker Button can never be size 0

vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
Apparently I'm not good at fixing NPEs
Fixes #10939
=> 10939 - NPE in SendToLocation

vassal-app/src/main/java/VASSAL/build/module/turn/TurnLevel.java
=> 10940 - NPE in TurnLevel

vassal-app/src/main/java/VASSAL/counters/Obscurable.java
https://forum.vassalengine.org/t/mask-deal-to-other-side-trouble/73420/2
=> 10964 - Fixed Deal-to-Side Mask bug - Finish evaluating expression properly

vassal-app/src/main/java/VASSAL/counters/Translate.java
=> 10970 Fix problem where rotated pieces did not move-fixed-distance in correct direction

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/java/VASSAL/configure/ListKeyCommandsDialog.java, vassal-app/src/main/java/VASSAL/launch/EditorWindow.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
More improvements for the ListKeyCommands dialog, per Dulgin's suggestions -- doesn't need a new issue number as it's just adding on.
(1) Dialog no longer modal
(2) Filter field no longer case sensitive
(3) "Jump to definition" right click option
=> List key improvements

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
=> 11067 - Fix NPE in SetupStack

vassal-app/src/main/java/VASSAL/launch/TilingHandler.java
Refactored TilingHandler so that VASL and VSQL need override only a small part of it.
=> Refactored TilingHandler

vassal-app/src/main/java/VASSAL/configure/ListKeyCommandsDialog.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
(no issue number as it's just part of List Key Commands). 
I also included rollover text on the table, for in case a particular field is too wide for its column.
=> "Path" column for List Key Commands

vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
(was putting extra warnings in the log)
=> 11105 - Added missing Editor.SendToLocation.getSendLocation translation key

vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceImage.java
Put the null check in the right place.
=> Fix NPE when duplicating GamePieceImage

vassal-app/src/main/java/VASSAL/build/module/GameState.java
I think I bungled this while changing stuff around for drag and drop, perhaps.
=> 11156 - Games incorrectly load normally during 'Load Continuation'

vassal-app/src/main/java/VASSAL/build/module/Console.java
Request from @riverwanderer
By adding "selected" into the command line the properties of currently selected pieces can be shown/set
`/property selected show LocationName`
=> Console can show/set properties of selected pieces

vassal-app/src/main/java/VASSAL/build/module/Chatter.java, vassal-app/src/main/java/VASSAL/build/module/Console.java
I keep wanting this totally standard CLI thing where you can hit up/down arrows to scroll around in previous commands you've typed.
=> Console supports up-arrow / down-arrow to e.g. repeat commands

vassal-app/src/main/java/VASSAL/launch/Editor.java, vassal-app/src/main/java/VASSAL/launch/Player.java
Check for lr.module == null in the right place.
=> Additional fix for Issue 11182

vassal-app/src/main/java/VASSAL/counters/BasicPiece.java, vassal-app/src/main/java/VASSAL/counters/TranslatableMessage.java
Gives these things better auto-descriptions in the Piece Definer display.
=> 11197 - Better auto-description for Translatable Message trait and BasicPiece

vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
=> 11188 - DoActionButton hotkeys were not found by search

vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Apparently another not-as-well-documented exception that can be thrown...
=> Catch InvalidDnDOperation exceptions when inappropriate drag-and-drops attempted

vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
(Joel's removeIf fix for Game Refresher concurrent problem)
=> Fix ConcurrentExecutionException in Game Refresher with Mats

vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java, vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Extends the principle I've been using to improve default descriptions of traits.
Displays...
Given Name - Name of Contained Piece - Location
Anything blank is omitted.
=> 11286 - Improved Setup Stack descriptions in editor

vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNotesController.java
Add notes from commands to end to preserve note order.
=> Delayed Notes from subsequent saves displayed out of order

pom.xml, vassal-app/src/main/java/VASSAL/build/module/Chatter.java, vassal-app/src/main/java/VASSAL/build/module/map/ImageSaver.java, vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java, vassal-app/src/main/java/VASSAL/build/module/properties/PropertySetter.java, vassal-app/src/main/java/VASSAL/chat/ui/LockableRoomTreeRenderer.java, vassal-app/src/main/java/VASSAL/chat/ui/RoomTreeRenderer.java, vassal-app/src/main/java/VASSAL/chat/ui/ShowServerStatusAction.java, vassal-app/src/main/java/VASSAL/counters/Deck.java, vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java, vassal-app/src/main/java/VASSAL/counters/PropertySheet.java, vassal-app/src/main/java/VASSAL/counters/RangeFilter.java, vassal-app/src/main/java/VASSAL/tools/concurrent/ConcurrentSoftHashMap.java, vassal-app/src/main/java/VASSAL/tools/imports/adc2/ADC2Module.java, vassal-app/src/test/resources/pmd.xml
Replaced deprecated EmptyFinallyBlock, EmptyInitializer, EmptyStatementBlock, EmptySwitchStatements, EmptySynchronizedBlock, EmptyTryBlock with EmptyControlStatement.
=> PMD Upgrade

vassal-app/src/main/java/VASSAL/build/module/GameState.java, vassal-app/src/main/java/VASSAL/command/PlayAudioClipCommand.java, vassal-app/src/main/java/VASSAL/counters/PlaySound.java
=> Don't play sounds while fast-forwarding a log

vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
Make sure all parts of configurer receive the same "setValue" value.
=> 11494 - Safer GKC Configurer for Fixed # From Deck

vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java
Also reset configurer values when re-opening after cancel.
=> 11570 - Update Module Extension window, add missing description.

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Apparently this needs a null check hohohohoho
=> Fix NPE I found (in earlier PR for 3.6.8) - no changelist item needed, bug hasn't shipped

release-prepare/pom.xml, vassal-app/pom.xml, vassal-deprecation/pom.xml, vassal-doc/pom.xml
This is just a little cleanup in the POM files to remove some maven Warning.
=> Improve poms

vassal-app/src/main/java/VASSAL/counters/Mat.java, vassal-app/src/main/java/VASSAL/counters/MatCargo.java
=> 11860 - Warn when same piece is both Mat and Mat Cargo

vassal-app/src/main/java/VASSAL/build/module/folder/PrototypeFolder.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
=> 11748 - NPE when cutting and pasting a prototype folder

vassal-app/src/main/java/VASSAL/build/module/properties/GlobalProperty.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
=> 11879 NPE when cutting and pasting a GlobalPropertyFolder

vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
Learned the hard way that it was a way to NPE. Sadly, learned it the day after 3.6.10, because of course I did.
=> 11890 - NPE when current-stack option used on non-stacking piece

vassal-app/src/main/java/VASSAL/counters/MatCargo.java
CAPTAIN PARENTHESES is here to save the day!
=> MatCargo's mat detection did unnecessary computations for lack of parentheses

vassal-app/src/main/java/VASSAL/configure/FormattedStringConfigurer.java
=> 11502 Insert items into formatted strings from drop-down list into the correctly selected position

vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNotesController.java
=> 11520 IndexOutOfBoundsException trying to open a private note

vassal-app/src/main/java/VASSAL/counters/TriggerAction.java
=> 11880 - Triggers set to count 0 times don't spuriously execute 1 time.

vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
@riverwanderer noticed that ActionButtons have the same problem as #11880 and are alas implemented independently.
=> 11993 - ActionButtons set to count 0 times don't spuriously execute 1 time.

vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
=> 11693 - Fixed exception when copying folders containing Mouse-over Stack Viewers

vassal-app/src/main/java/VASSAL/counters/Deck.java
Fixes #11173 
Fixes #12015 
Fixes #11955
=> 11173 - Fixed crash in sorting a deck

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Miro had a crash today in SetupStack, and this seemed like a possible scenario
https://discord.com/channels/740127632586178572/911006365626036294/1076144291317035018
=> 12016 - Fix a possible crash scenario in At-Start Stacks

vassal-app/src/main/java/VASSAL/configure/ChooseComponentDialog.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
=> 11451 - Don't permit drag-and-drop within PlaceMarker, Replace with Other selection dialogs

vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
Fixes #11967 
@riverwanderer When you have a chance, give a test and see if this corrects your issue
=> 11967 - When dragging piece out of face-down deck, use unrotated shape

vassal-app/src/main/java/VASSAL/counters/DeckManager.java
=> 12037 - Fix concurrent modification exception in Decks

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Fixes #12042 
Fixes #12008 
Fixes #11651
=> 12042 - Fix bug when copying Decks and At-Start Stacks to other maps

vassal-app/src/main/java/VASSAL/counters/BasicPiece.java, vassal-app/src/main/java/VASSAL/counters/Decorator.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
=> 12003 - OldDeckName now supported as a piece property

vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java, vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java, vassal-app/src/main/java/VASSAL/build/module/Map.java, vassal-app/src/main/java/VASSAL/build/module/folder/MapSubFolder.java
Fixes #10820
@riverwanderer Another from your wishlist ... seems to work for me but please give it a more thorough spin!
=> 10820 - Make Action Button available on all windows where other similar buttons (eg GKC, Multi-Action, etc) are available

vassal-app/src/main/java/VASSAL/counters/Deck.java
=> 12063 - Fixed Deck save/load hotkeys being mixed up

vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java, vassal-app/src/main/java/VASSAL/tools/menu/MenuItemProxy.java, vassal-app/src/main/java/VASSAL/tools/menu/MenuProxy.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameModule.adoc
Special gift for Command & Colors :)
Fixes #11506
=> 11506 - Predefined Setup "menus" with blank names will not be shown

Makefile, pom.xml, release-prepare/pom.xml, vassal-agent/pom.xml, vassal-agent/src/main/java/org/vassalengine/agent/Agent.java, vassal-agent/src/main/java/org/vassalengine/agent/Win32ShellFolderManager2Interceptor.java, vassal-app/src/main/java/VASSAL/launch/AbstractLaunchAction.java
Intercept sun.awt.shell.Win32ShellFolderManager2.compareShellFolders().
It incorrectly handles some cases where only one of the folders being compared is special.
=> Work around Java bug which prevents displaying Windows file dialogs

vassal-app/src/main/java/VASSAL/tools/swing/DataArchiveHTMLEditorKit.java
This fixes a problem introduced in 3.7.0-beta1, so I don't know if it gets a permanent changelist number or not, but if it does it would be 12175
=> Fix Stretchy Images in chat

vassal-app/src/main/java/VASSAL/counters/Embellishment.java
This stuff wasn't causing the reported problem, but I did realize I ought to harden it up a bit more because I thought of an edge case where it *could* cause a problem.
This is just an "internal patch" to 3.7.0 beta, so probably doesn't need a number
=> Harden Embellishment a bit more

vassal-app/src/main/java/VASSAL/counters/AreaOfEffect.java
https://forum.vassalengine.org/t/3-7-0b2-not-displaying-some-layers/76864
=> 12205 - Area of Effect trait was eating other traits' visibility info in some cases

vassal-app/src/main/java/VASSAL/counters/Pivot.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Pivot.adoc
=> 12184 - Pivot can have two key commands/angles

pom.xml, vassal-agent/pom.xml, vassal-app/pom.xml, vassal-deprecation/pom.xml
--release additionally sets the -bootclasspath, which is needed to ensure compatibility of class files.
For more details, see: https://stackoverflow.com/a/43103038/181106
=> Set --release instaed of --source and --target when building. --release

vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java, vassal-app/src/main/java/VASSAL/counters/Stack.java
=> Prevent NPE in MouseOverStackViewer trying to show top piece of empty stack

vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java, vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java
(description field was being suppressed but shouldn't have been)
=> 12302 - Description field now properly appears with Startup GKC set to send Global Hotkey

vassal-app/src/main/java/VASSAL/tools/LaunchButton.java
@riverwanderer give a try when the build comes up?
=> 12303 - Dynamic button text was resolved too soon

vassal-app/src/main/java/VASSAL/configure/BeanShellFunctionMenu.java, vassal-app/src/main/java/VASSAL/counters/Attachment.java, vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/main/resources/VASSAL/script/init_expression.bsh, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/ExpressionRange.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/ExpressionSumCount.adoc
=> 12323 - Add Beanshell Range functions

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Uniformly handle addition of tree elements.
=> Uniformly handle addition of standard and imported Configurables

vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java, vassal-app/src/main/java/VASSAL/counters/Comment.java, vassal-app/src/main/java/VASSAL/counters/PieceCloner.java, vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
=> 12492 - Add Comment trait

vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Start new Decks and At-start Stacks on the board at 100,100 where they can be seem
=> 12509 - Allow and empty Deck or At-start Stack to be repositioned

vassal-app/src/main/java/VASSAL/configure/BeanShellFunctionMenu.java, vassal-app/src/main/java/VASSAL/script/AbstractInterpreter.java, vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java, vassal-app/src/main/java/VASSAL/tools/swing/DialogCloser.java, vassal-app/src/main/resources/VASSAL/i18n/Editor.properties, vassal-app/src/main/resources/VASSAL/script/init_expression.bsh
Added Sleep(ms) to sleep for a bit.
Added Alert(Text, ms) to close Alert box after a time
=> 12566 Add Beanshell function to add Sleep/Delay processing

vassal-app/src/main/java/VASSAL/build/module/Chatter.java
The caret is ugly and also useless, since the chat pane isn't editable.
=> Hide caret in chat pane

vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
=> Translate side names in change sides message

vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Attempt to resolve issue #12657 (current side).
=> Translate current side before checking for "next side".

vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Possible fix for #12645 - suspect that Side is not localized before testing for removal from Available sides.
=> 12645 Respect localisation when filtering sides

vassal-app/src/main/java/VASSAL/tools/filechooser/FileChooser.java
Reset of previous messed up PR.
=> Update selectDotSavFile() description (vsav).

vassal-app/src/main/java/VASSAL/counters/Labeler.java
=> 12784 - Fix rendering of external Text Label images

vassal-app/src/main/java/VASSAL/build/module/map/LayeredPieceCollection.java, vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Also Change Game Piece Layers to be non-mandatory
=> 12825 Allow Unique components to be copied; change Game Piece Layers to be non-mandatory.

vassal-app/src/main/java/VASSAL/command/CommandFilter.java
Don't ask me why this broke it, I have no idea.
=> 12830 Prevent Load Continuation from auto-forwarding to end of log

vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/ColorManager.java, vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/FontManager.java, vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceImageDefinitions.java
This basically just undoes the fix for 12824 and does a minor tidy up.
=> 12846 Fix missing custom colors and font styles in Game Piece Layouts

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java, vassal-app/src/main/java/VASSAL/counters/Comment.java, vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
=> Number in-use traits in Piece Definer

vassal-app/pom.xml, vassal-app/src/main/java/VASSAL/chat/HttpRequestWrapper.java
See https://github.com/apache/httpcomponents-client/pull/512
=> Revert httpclient5 to 5.2.1 while we wait for a Proxy fix

vassal-app/src/main/java/VASSAL/chat/ui/RoomTreeRenderer.java
=> 12981 Fixed IndexOutOfBoundsException in empty chat room

vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java, vassal-app/src/main/java/VASSAL/tools/DataArchive.java
=> 13021 - Allow wizard to load setups from extensions

vassal-app/src/main/java/VASSAL/build/module/ExtensionElement.java
=> 13057-Remove Unused Images does not find any images in use in an Extension

vassal-app/src/main/java/VASSAL/build/module/AttachmentManager.java
=> 13073 - Attachments are lost after Undo

vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Added some defensive programming. This really shouldn't happen.
=> 13161 - Prevent ArrayIndexOutOfBounds during search

vassal-app/src/main/java/VASSAL/build/GameModule.java, vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java, vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java, vassal-app/src/main/java/VASSAL/counters/KeyBuffer.java
Adds missing case of DnD after move key to PR #13121
Also includes a framework for reporting on multi-piece UI gesture processing in 3.8 (Not enabled in this PR)
=> 13174 - Update Labels on remote maps after DragnDrop

vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
Reproduced easily and tested fix resolves issue,
=> 13400 - Prevent crashes when refreshing counters with fewer Can Rotate facings

vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java, vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java
A slightly improved fix to handle reporting correctly at 2 different levels.
=> 13359 - Improved fix

vassal-app/src/main/java/VASSAL/build/module/properties/AbstractScenarioProperty.java, vassal-app/src/main/java/VASSAL/build/module/properties/ScenarioPropertiesOptionTab.java, vassal-app/src/main/java/VASSAL/configure/StringConfigurer.java, vassal-app/src/main/java/VASSAL/configure/StringEnumConfigurer.java, vassal-app/src/main/java/VASSAL/configure/TranslatingStringEnumConfigurer.java
Scenario Options Tabs and pages now have Help.
=> 13450 - Make Locked Scenario Options more legible

vassal-doc/src/main/readme-referencemanual/ReferenceManual/Extension.adoc
=> Bring section up to date with Module Library interface.

vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Marker.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/Replace.adoc
=> Fix offset placement for Place Marker & Replace with Other

vassal-app/src/main/java/VASSAL/tools/Mp3AudioClip.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Converts exceptions to a logged error message.
=> Suppress exceptions when establishing an MP3 audio stream

vassal-app/src/main/java/VASSAL/build/module/DiceButton.java, vassal-app/src/main/java/VASSAL/build/module/RandomTextButton.java
Also, fix an issue whereby Random Text Button does not implement results sorting. Caution: AI-mediated work.
=> Add dice & random text button summary output property

vassal-app/src/main/java/VASSAL/build/module/DiceButton.java, vassal-app/src/main/java/VASSAL/build/module/RandomTextButton.java, vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties, vassal-doc/src/main/designerguide/generating-random-results.adoc, vassal-doc/src/main/readme-referencemanual/ReferenceManual/DiceButton.adoc
Localisation support for summary report format.
Documentation.
Completes #13957 .
=> Finishing off DiceButton & RandomTextButton summary output feature
